import {expect,it} from "vitest";
import {build} from "esbuild";
import path from "node:path";
import {mkdir,readFile,writeFile} from "node:fs/promises";
import puppeteer from "puppeteer";
it("formal menu applies rendered particles and clears paid3D selection when switched to free",async()=>{
 const bundle=await build({stdin:{resolveDir:process.cwd(),loader:"tsx",contents:`import React,{useState}from'react';import{createRoot}from'react-dom/client';import Effects from'./client/src/components/code-motion/CodeMotionEffects';import Preview from'./client/src/components/code-motion/CodeMotionPreview';import{codeMotionProjectSchema,compileCodeMotion}from'./shared/codeMotion';const initial=codeMotionProjectSchema.parse({id:'11111111-1111-4111-8111-111111111111',brief:{title:'特效',request:'预览特效',style:'scenes',duration:20,generationTier:'paid',orientation:'landscape',images:[],data:[]},plan:{version:1,summary:'四镜',scenes:Array.from({length:4},(_,i)=>({heading:'场景',body:'',duration:5,direction:'图形画面',composition:{id:'s'+i,duration:5,elements:[{id:'shape',type:'shape',shape:'rect',transform:{x:.5,y:.5,fill:'#88aaee'}}]}}))}});function App(){const[p,setP]=useState(initial);globalThis.project=p;return <><Effects project={p} disabled={false} paidAvailable={true} threeDAvailable={true} onChange={setP}/><Preview key={JSON.stringify(p.plan)} spec={compileCodeMotion(p.brief,p.plan)}/></>}createRoot(document.getElementById('root')).render(<App/>);`},bundle:true,write:false,format:"iife",platform:"browser",jsx:"automatic",alias:{"@":path.resolve("client/src"),"@shared":path.resolve("shared")},define:{"process.env.NODE_ENV":'"development"',"import.meta.env":"{}"}});
 const browser=await puppeteer.launch({headless:true});
 try{const page=await browser.newPage();const errors:string[]=[];page.on("pageerror",e=>errors.push(String(e)));await page.setRequestInterception(true);page.on("request",async r=>{const u=new URL(r.url());if(u.pathname.startsWith("/art-motion/engine/")){const name=path.resolve("client/public"+u.pathname);if(!name.startsWith(path.resolve("client/public/art-motion/engine")+path.sep))return void r.abort();try{await r.respond({status:200,contentType:u.pathname.endsWith(".js")?"application/javascript":u.pathname.endsWith(".html")?"text/html":"application/octet-stream",body:await readFile(name)});}catch{await r.abort();}}else if(r.isNavigationRequest())await r.respond({status:200,contentType:"text/html",body:'<div id="root"></div>'});else await r.abort();});await page.goto("http://localhost:41948/");await page.addScriptTag({content:bundle.outputFiles[0].text});await page.waitForSelector('[aria-label="选择特效与能力"]');
 await page.select('[aria-label="选择特效与能力"]',"model3d");expect(await page.$eval('a[href="/manhua-projects"]',e=>e.textContent)).toContain("打开");
 await page.select('[aria-label="生成方案"]',"free");expect(await page.$eval('[aria-label="选择特效与能力"]',e=>(e as HTMLSelectElement).value)).toBe("fade");expect(await page.$$eval('option[value="model3d"],option[value="splat3d"]',es=>es.every(e=>(e as HTMLOptionElement).disabled))).toBe(true);
 await page.select('[aria-label="选择特效与能力"]',"orbit");await page.evaluate(()=>Array.from(document.querySelectorAll("button")).find(b=>b.textContent?.includes("采用到代码镜头"))!.click());
 await page.waitForFunction(()=>(globalThis as any).project.plan.scenes.every((s:any)=>s.composition.elements.some((e:any)=>e.type==="particles"&&e.motion==="orbit")));
 await page.waitForFunction(()=>document.querySelector('[role="status"]')?.textContent?.includes("已采用"));
 const frame=await(await page.$("iframe"))!.contentFrame();await frame!.waitForFunction("window.__productReady || window.__bootFailed",{timeout:25000});
 const pixels=await frame!.evaluate(()=>{const w=window as any;if(w.__bootFailed)throw Error(w.__bootFailed);return [0,2].map(t=>{w.renderFrame(t);const a=w.__canvas.getContext('2d').getImageData(0,0,w.__canvas.width,w.__canvas.height).data;let hash=0;for(let i=0;i<a.length;i+=64)hash=(Math.imul(hash,31)+a[i]+a[i+1]+a[i+2])>>>0;return hash;});});expect(new Set(pixels).size).toBe(2);expect(errors).toEqual([]);
 const dir=path.resolve("docs/evidence/code-motion-1011/video-edit/browser");await mkdir(dir,{recursive:true});await page.screenshot({path:path.join(dir,"effects-free-rendered.png"),fullPage:true});await writeFile(path.join(dir,"effects-menu-browser.json"),JSON.stringify({free3DDisabled:true,paidSelectionCleared:true,renderFrameHashes:pixels,errors},null,2));
 }finally{await browser.close();}
},60000);
