import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { ManhuaSceneSpacePanel } from "../components/canvas/ManhuaSceneSpacePanel";
import { normalizeCanvasBlock } from "./canvasTypes";
import { projectManhuaSpatialStoryCuesForBgm } from "@shared/manhuaSpatialStoryCue";
import { expect, it } from "vitest";
import { selectCurrentManhuaSpatialContexts, spawnManhuaDramaStudio, expandManhuaShotKeyartsAfterReverse, ensureManhuaFragmentClips, queuedManhuaClipBlocks } from "./canvasDramaStudio";
import { normalizeManhuaCustomAssetRefs } from "@shared/manhuaCustomAssetRefs";
import type { ManhuaSceneSpace } from "@shared/manhuaSceneSpace";
it("实际段编译消费同一场景空间版本，换图后停止注入", () => {
 const model = "seedance-2.0-mini";
 const assetCanon = { characters: [{ id: "wa_char_ajing", role: "character" as const, nameZh: "阿菁", lookZh: "青衣", promptZh: "阿菁青衣" }], props: [], locations: [], episodeMainSceneId: {} };
 const spawned = spawnManhuaDramaStudio({ topic: "医馆后院", episodeIndex: 1, videoModel: model });
 const reverse = spawned.blocks.find(b => b.id.startsWith("reverse-"))!;
 const expanded = expandManhuaShotKeyartsAfterReverse(spawned.blocks.map(b => b.id === reverse.id ? { ...b, status: "done" as const, outputText: Array.from({ length: 18 }, (_, i) => `${i + 1}. 第${i + 1}镜：医馆后院，阿菁从木门走入诊室`).join("\n") } : b), spawned.edges, reverse.id);
 const blocks = expanded.blocks.map(b => b.id.startsWith("keyart-") ? { ...b, status: "done" as const, outputUrl: `https://test.example/${b.id}.jpg` } : b);
 const space: ManhuaSceneSpace = { version: 1, sourceRefId: "clinic", sourceVersion: "gs://test/clinic.png", revision: 7, status: "approved", sourceNoteZh: "原稿医馆门槛", zones: [{ id: "yard", labelZh: "后院", fixedFeaturesZh: "井台在东" }, { id: "room", labelZh: "诊室", fixedFeaturesZh: "药柜在北" }], passages: [{ id: "door", fromId: "yard", toId: "room", labelZh: "木门", bidirectional: true }] };
 const refs = normalizeManhuaCustomAssetRefs([{ id: "clinic", role: "scene", labelZh: "医馆后院", url: "https://test.example/clinic.png", gcsUri: space.sourceVersion, sceneSpace: space }, { id: "cust_photo_ajing", role: "character", refDuty: "identity", claimedAnchorIds: ["wa_char_ajing"], primaryBindings: [{ anchorId: "wa_char_ajing", duty: "identity" }], labelZh: "阿菁", url: "https://test.example/ajing.png" }]);
 const compile = (customRefs: typeof refs) => queuedManhuaClipBlocks(ensureManhuaFragmentClips(blocks, expanded.edges, 1, { videoModel: model, assetCanon, customRefs }).blocks, 1, model).map(b => b.prompt).join("\n");
 expect(compile(refs)).toContain("【场景空间·clinic·v7】");
 expect(compile(refs)).toContain("后院↔诊室（木门）");
 const changedRefs = refs.map(ref => ({ ...ref, gcsUri: "gs://test/clinic-v2.png" }));
 expect(compile(changedRefs)).not.toContain("【场景空间");
 const initial = ensureManhuaFragmentClips(blocks, expanded.edges, 1, { videoModel: model, assetCanon, customRefs: refs });
 const firstClip = queuedManhuaClipBlocks(initial.blocks, 1, model)[0];
 const context = firstClip.manhuaSpatialContext!;
 expect(context.sceneIds).toContain("clinic");
 expect(context.actorIds).toEqual(["wa_char_ajing"]);
 expect(context.shotIds.length).toBeGreaterThan(0);
 const scope = { episode: context.episode, segmentIndex: context.segmentIndex, shotId: context.shotIds[0], sourceRevision: context.sourceRevision };
 const actorId = context.actorIds[0];
 const routedRefs = refs.map(ref => ref.id !== "clinic" ? ref : ({ ...ref, sceneSpace: { ...space, actorPositions: [{ id: "pos", scope, actorId, zoneId: "yard", positionZh: "门槛外", designPosition: { x: 0.25, y: 0.75, facingDegrees: 135 }, facingZh: "向诊室", visibility: "offscreen" as const, occlusionZh: "画外后院等候", sourceZh: "本镜可拍表" }], storyCues: [{ id: "cue", scope, actorId, passageId: "door", eventZh: "听见诊室呼救，停下脚步", emotionZh: "犹疑变为决心", musicCue: "breath" as const, musicNoteZh: "音乐停顿，保留呼救", sourceZh: "本镜可拍表" }] } }));
 const panelProps = { asset: routedRefs[0], actors: assetCanon.characters.map(c => ({ id: c.id, labelZh: c.nameZh })), scopes: [{ ...scope, labelZh: "本镜" }], onChange: () => {} };
 const markup = renderToStaticMarkup(createElement(ManhuaSceneSpacePanel, panelProps));
 expect(markup).toContain('data-design-x="0.25"');
 expect(markup).toContain('data-design-y="0.75"');
 expect(markup).toContain('data-facing-degrees="135"');
 expect(markup).toContain('rotate(135)');
 const invalidActorMarkup = renderToStaticMarkup(createElement(ManhuaSceneSpacePanel, { ...panelProps, actors: [] }));
 expect(invalidActorMarkup).toContain("部分人物、镜段或剧本版本已失效，请重新绑定");
 expect(invalidActorMarkup).toMatch(/<button[^>]*disabled=""[^>]*>确认并采用空间关系/);
 const invalidShotMarkup = renderToStaticMarkup(createElement(ManhuaSceneSpacePanel, { ...panelProps, scopes: [{ ...scope, shotId: "missing", labelZh: "其它镜" }] }));
 expect(invalidShotMarkup).toContain("部分人物、镜段或剧本版本已失效，请重新绑定");
 expect(renderToStaticMarkup(createElement(ManhuaSceneSpacePanel, { ...panelProps, scopes: [] }))).toMatch(/<button[^>]*disabled=""[^>]*>确认并采用空间关系/);
 const routed = ensureManhuaFragmentClips(initial.blocks, initial.edges, 1, { videoModel: model, assetCanon, customRefs: routedRefs });
 const normalized = queuedManhuaClipBlocks(routed.blocks, 1, model).map(b => normalizeCanvasBlock(JSON.parse(JSON.stringify(b))));
 expect(normalized[0].manhuaSpatialContext).toEqual(context);
 expect(normalized[0].prompt).toContain("画外后院等候");
 expect(normalized[0].prompt).toContain("听见诊室呼救，停下脚步");
 const projection = projectManhuaSpatialStoryCuesForBgm(routedRefs, normalized.flatMap(b => b.manhuaSpatialContext ? [b.manhuaSpatialContext] : []));
 expect(projection.cues.map(c => c.id)).toEqual(["cue"]);
 expect(projection.hasSilenceBreak).toBe(true);
 expect(projection.noteZh).toContain("音乐停顿，保留呼救");
 const rewrittenBlocks = routed.blocks.map(b => b.id === reverse.id ? { ...b, outputText: String(b.outputText).replaceAll("阿菁从木门走入诊室", "阿菁转身离开木门，返回后院") } : b);
 expect(projectManhuaSpatialStoryCuesForBgm(routedRefs, selectCurrentManhuaSpatialContexts(routed.blocks, 1, model)).cues).toHaveLength(1);
 expect(projectManhuaSpatialStoryCuesForBgm(routedRefs, selectCurrentManhuaSpatialContexts(rewrittenBlocks, 1, model)).cues).toHaveLength(0);
 const rewritten = ensureManhuaFragmentClips(rewrittenBlocks, routed.edges, 1, { videoModel: model, assetCanon, customRefs: routedRefs });
 const rewrittenClips = queuedManhuaClipBlocks(rewritten.blocks, 1, model);
 expect(rewrittenClips[0].manhuaSpatialContext!.shotIds).toEqual(context.shotIds);
 expect(rewrittenClips[0].manhuaSpatialContext!.sourceRevision).not.toEqual(context.sourceRevision);
 expect(rewrittenClips[0].prompt).not.toContain("听见诊室呼救，停下脚步");
 expect(projectManhuaSpatialStoryCuesForBgm(routedRefs, rewrittenClips.flatMap(b => b.manhuaSpatialContext ? [b.manhuaSpatialContext] : [])).cues).toHaveLength(0);
 expect(renderToStaticMarkup(createElement(ManhuaSceneSpacePanel, { ...panelProps, scopes: [{ ...scope, sourceRevision: rewrittenClips[0].manhuaSpatialContext!.sourceRevision, labelZh: "改写后的本镜" }] }))).toMatch(/<button[^>]*disabled=""[^>]*>确认并采用空间关系/);
 const annotated = initial.blocks.map(b => b.kind === "video" ? { ...b, prompt: `${b.prompt}\n\n【用户补充】\n保留门外反应镜` } : b);
 const refreshed = ensureManhuaFragmentClips(annotated, initial.edges, 1, { videoModel: model, assetCanon, customRefs: changedRefs });
 const refreshedClips = queuedManhuaClipBlocks(refreshed.blocks, 1, model);
 expect(refreshedClips.length).toBeGreaterThan(0);
 for (const clip of refreshedClips) {
   expect(clip.prompt).not.toContain("【场景空间");
   expect(clip.prompt).toContain("保留门外反应镜");
 }

});
