import { beforeAll, afterAll, expect, it } from "vitest";
import { build } from "esbuild";
import puppeteer, { type Browser, type Page } from "puppeteer";
import path from "node:path";
let browser: Browser, code: string;
beforeAll(async()=>{
 const result=await build({stdin:{contents:`import React,{useState,useRef} from 'react';import{createRoot}from'react-dom/client';import{NovelVoiceRevision}from'./client/src/components/canvas/NovelVoiceRevision';import{emptyNovelWorkspace}from'./client/src/lib/novelWorkspace';import{readNovelWorkspaceDb,saveNovelWorkspaceDb}from'./client/src/lib/novelWorkspaceDb';import{applyNovelVoiceCandidate}from'./client/src/lib/novelVoiceEditing';
 const f=globalThis.fixture={messages:[],sockets:[],allow:true,saveFail:false,saves:0};window.confirm=()=>f.allow;
 class Audio {resume(){return Promise.resolve()}close(){return Promise.resolve()}}window.AudioContext=Audio;
 class WS{static OPEN=1;readyState=1;bufferedAmount=0;constructor(){f.sockets.push(this);setTimeout(()=>this.onopen?.(),0)}send(s){const m=JSON.parse(s);f.messages.push(m);if(m.type==='start')this.emit({type:'status',text:'ready',ready:true})}emit(m){this.onmessage?.({data:JSON.stringify(m)})}close(){this.readyState=3}}window.WebSocket=WS;
 function App(){const[draft,setDraft]=useState({...emptyNovelWorkspace(),chapters:['第一集\\n门外下着雨。\\n裴昭递来药碗。','第二集\\n沈昀入宫。']});const r=useRef(draft);r.current=draft;const raw=useRef(null);f.draft=()=>r.current;f.readSaved=()=>readNovelWorkspaceDb('7');f.edit=()=>{r.current={...r.current,chapters:['用户新正文',r.current.chapters[1]]};setDraft(r.current)};return <><textarea aria-label='正文' readOnly value={draft.chapters[0]}/><NovelVoiceRevision scopeKey={'7:'+draft.roundId} context='作品' onUse={()=>{}} onAskAdvisor={async()=>''} getWorkspace={()=>r.current} onApplyRevision={async(c,signal)=>{const before=r.current;const next=await applyNovelVoiceCandidate(before,c);if(signal.aborted||r.current!==before)throw Error('正文变化');if(f.saveFail)throw Error('模拟存储故障');raw.current=await saveNovelWorkspaceDb('7',raw.current,next,'voice-'+c.id);f.saves++;r.current=next;setDraft(next)}}/></>};createRoot(document.getElementById('root')).render(<App/>);`,loader:'tsx',resolveDir:process.cwd()},bundle:true,write:false,jsx:'automatic',format:'iife',platform:'browser',alias:{'@':path.resolve('client/src'),'@shared':path.resolve('shared')},define:{'process.env.NODE_ENV':'"development"','import.meta.env':'{}'},plugins:[{name:'boundaries',setup(b){b.onResolve({filter:/useAuth$/},()=>({path:'auth',namespace:'mock'}));b.onResolve({filter:/longJobsFlyOrigin$/},()=>({path:'origin',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},a=>({contents:a.path==='auth'?"export const useAuth=()=>({user:{id:7,role:'admin'}})":"export const withLongJobsFlyDirect=p=>p;export const flyHealthProbeOriginForUrl=()=>null;",loader:'js'}))}}]});code=result.outputFiles[0].text;browser=await puppeteer.launch({headless:true});
},60000);
afterAll(async()=>{await browser?.close()});
async function page(){const context=await browser.createBrowserContext();const p=await context.newPage();p.setDefaultTimeout(6000);await p.setRequestInterception(true);p.on('request',r=>r.isNavigationRequest()?void r.respond({status:200,contentType:'text/html',body:'<div id="root"></div>'}):void r.abort());await p.goto('http://localhost:41849');await p.addScriptTag({content:code});await click(p,'打开');await click(p,'开始讨论');await p.waitForFunction(()=>document.body.textContent?.includes('ready'));return p;}
async function click(p:Page,t:string){await p.evaluate(t=>{const b=Array.from(document.querySelectorAll('button')).find(b=>b.textContent?.includes(t));if(!b)throw Error(t);b.click()},t)}
async function tool(p:Page,id:string,action:any){await p.evaluate(({id,action})=>(globalThis as any).fixture.sockets[0].emit({type:'novelEdit',id,action}),{id,action});await p.waitForFunction(id=>(globalThis as any).fixture.messages.some((m:any)=>m.type==='toolResult'&&m.id===id),{},id);return p.evaluate(id=>(globalThis as any).fixture.messages.find((m:any)=>m.type==='toolResult'&&m.id===id).text,id);}
async function preview(p:Page){const r=JSON.parse(await tool(p,'read',{action:'read',episode:1}));return JSON.parse(await tool(p,'preview',{action:'preview',episode:1,revision:r.revision,edits:[{before:'裴昭递来药碗。',after:'裴昭收回药碗：先告诉我，你替谁办事？'}],summary:'让裴昭主动试探'}));}
it('真实语音工具到正文：预览不修改、取消不写、确认写入IndexedDB并保留旧版，重复ID不重做',async()=>{
 const p=await page(), c=await preview(p);expect(await p.$eval('[aria-label="正文"]',e=>(e as HTMLTextAreaElement).value)).toContain('递来药碗');
 await p.evaluate(()=>(globalThis as any).fixture.allow=false);expect(await tool(p,'cancel',{action:'apply',candidateId:c.candidateId})).toContain('取消');
 await p.evaluate(()=>(globalThis as any).fixture.allow=true);expect(await tool(p,'apply',{action:'apply',candidateId:c.candidateId})).toContain('实际写入');
 const saved=await p.evaluate(async()=>(await(globalThis as any).fixture.readSaved()).value);expect(saved.chapters[0]).toContain('收回药碗');expect(saved.chapters[1]).toBe('第二集\n沈昀入宫。');expect(saved.chapterVersions[0].text).toContain('递来药碗');
 await p.evaluate(id=>(globalThis as any).fixture.sockets[0].emit({type:'novelEdit',id:'apply',action:{action:'apply',candidateId:id}}),c.candidateId);expect(await tool(p,'again',{action:'apply',candidateId:c.candidateId})).toContain('保存过');expect(await p.evaluate(()=>(globalThis as any).fixture.saves)).toBe(1);await p.browserContext().close();
});
it('正文已手改或存储失败时不得冒称成功，候选稿保留',async()=>{
 const p=await page(),c=await preview(p);await p.evaluate(()=>(globalThis as any).fixture.saveFail=true);expect(await tool(p,'failed',{action:'apply',candidateId:c.candidateId})).toContain('存储故障');expect(await p.evaluate(()=>(globalThis as any).fixture.saves)).toBe(0);
 expect(await p.$eval('[aria-label="正文"]',e=>(e as HTMLTextAreaElement).value)).toContain('递来药碗');
 await p.evaluate(()=>{(globalThis as any).fixture.saveFail=false;(globalThis as any).fixture.edit()});expect(await tool(p,'stale',{action:'apply',candidateId:c.candidateId})).toContain('变化');expect(await p.$eval('[aria-label="正文"]',e=>(e as HTMLTextAreaElement).value)).toBe('用户新正文');await p.browserContext().close();
});
