import {it,expect} from 'vitest';
import {build} from 'esbuild';
import puppeteer from 'puppeteer';
import path from 'node:path';
import {novelMockTransport} from './novelWorkspace.browser.fixture';
it('实际小说页切集即时读正文，语音确认写回并重开恢复，旧版可找回',async()=>{
 const built=await build({stdin:{resolveDir:process.cwd(),loader:'tsx',contents:`import React from 'react';import{createRoot}from'react-dom/client';import{NovelAdaptationWorkspace}from'./client/src/pages/NovelAdaptation';import{emptyNovelWorkspace}from'./client/src/lib/novelWorkspace';import{readNovelWorkspaceDb,saveNovelWorkspaceDb}from'./client/src/lib/novelWorkspaceDb';
 window.confirm=()=>true;globalThis.voiceFixture={};(async()=>{const loaded=await readNovelWorkspaceDb('1');if(loaded.raw===null){const draft={...emptyNovelWorkspace(),topic:'隔离语音作品',chapters:['第一集：雨落屋檐。','第二集：裴昭递来药碗。','第三集：沈昀入宫。']};await saveNovelWorkspaceDb('1',loaded.raw,draft)}createRoot(document.getElementById('root')).render(<NovelAdaptationWorkspace userId='1'/>);})();`},bundle:true,write:false,outdir:'voice-page-test',platform:'browser',format:'iife',jsx:'automatic',alias:{'@':path.resolve('client/src'),'@shared':path.resolve('shared')},external:['pdfjs-dist','tesseract.js'],define:{'process.env.NODE_ENV':'"test"','import.meta.env':'{}'},plugins:[{name:'boundary',setup(b){b.onResolve({filter:/^@\/lib\/trpc$/},()=>({path:'trpc',namespace:'mock'}));b.onResolve({filter:/useAuth$/},()=>({path:'auth',namespace:'mock'}));b.onResolve({filter:/\.\/CreativeVoicePanel$/},()=>({path:'voice',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},a=>({loader:'tsx',resolveDir:process.cwd(),contents:a.path==='trpc'?novelMockTransport:a.path==='auth'?`export const useAuth=()=>({user:{id:1,role:'admin'},loading:false});`:`export function CreativeVoicePanel(props){globalThis.voiceFixture.props=props;return <div>语音真实页面桥</div>}` }));}}]});
 const code=built.outputFiles.find(f=>f.path.endsWith('.js'))!.text;
 const browser=await puppeteer.launch({headless:true});try{const p=await browser.newPage();p.setDefaultTimeout(7000);await p.setRequestInterception(true);p.on('request',r=>r.isNavigationRequest()?void r.respond({status:200,contentType:'text/html',body:'<div id="root"></div>'}):void r.abort());await p.goto('http://localhost:41850/');await p.addScriptTag({content:code});await p.waitForFunction(()=>{const p=(globalThis as any).voiceFixture.props;return p && !p.disabled && JSON.parse(p.context).chapterCount===3});
 const result=await p.evaluate(()=>{const props=(globalThis as any).voiceFixture.props;return props.onNavigate({episode:2,label:'第二集'})});expect(JSON.parse(result)).toMatchObject({episode:2,text:'第二集：裴昭递来药碗。'});
 await p.waitForFunction(()=>JSON.parse((globalThis as any).voiceFixture.props.context).activeEpisode===2);
 const adopted=await p.evaluate(async()=>{const f=(globalThis as any).voiceFixture;const signal=new AbortController().signal;const read=JSON.parse(await f.props.onNovelAction({action:'read',episode:2},signal));const preview=JSON.parse(await f.props.onNovelAction({action:'preview',episode:2,revision:read.revision,edits:[{before:'裴昭递来药碗。',after:'裴昭收回药碗：先说清楚，你替谁办事？'}],summary:'女主主动试探'},signal));return f.props.onNovelAction({action:'apply',candidateId:preview.candidateId},signal)});expect(adopted).toContain('实际写入');
 const saved=await p.evaluate(()=>(globalThis as any).readDraft());expect(saved.chapters[0]).toBe('第一集：雨落屋檐。');expect(saved.chapters[1]).toContain('收回药碗');expect(saved.chapterVersions[0].text).toBe('第二集：裴昭递来药碗。');expect(await p.evaluate(()=>(globalThis as any).archives())).toBe(true);
 await p.reload();await p.addScriptTag({content:code});await p.waitForFunction(()=>{const p=(globalThis as any).voiceFixture.props;return p && !p.disabled && JSON.parse(p.context).chapterCount===3});const restored=JSON.parse(await p.evaluate(()=>(globalThis as any).voiceFixture.props.onNovelAction({action:'read',episode:2},new AbortController().signal)));expect(restored.text).toBe(saved.chapters[1]);
 }finally{await browser.close()}
},60000);
