import {expect,it} from 'vitest';
import {build} from 'esbuild';
import puppeteer from 'puppeteer';
import path from 'node:path';
import {existsSync} from 'node:fs';
it('用户原话要求改第一集：候选先保存、确认后套用，第二集不变，白模上下文不劫持改稿',async()=>{
 const result=await build({stdin:{resolveDir:process.cwd(),loader:'tsx',contents:`
import React,{useState}from'react';import{createRoot}from'react-dom/client';import Panel from './client/src/components/canvas/ManhuaCreativeAdvisorPanel';
const f=globalThis.fixture={requests:[],writes:[],backups:[]};const original='场次 E1-S1：沈昀在文书库醒来，纸上的官印映着窗外的天光。他听到周慎走近，忙将文书压在手底，努力稳住呼吸。';const revised=original+'天光落在纸页上，架间保持阴影，周慎停在门口，看清他收纸的动作。';f.revised=revised;
function App(){const[body,setBody]=useState(original);const[focus,setFocus]=useState(2);f.body=body;return <Panel open userId='1' confirmedProjectVersion='voice-rewrite-test' onClose={()=>{}} templates={[]} onRequestTrial={()=>{}} previsIssue='未打开白模' worldTarget={{assetId:'old-world-target'}} episodeWorkspace={{episodes:[{index:1,title:'文书库',body,endHook:'门后有人'},{index:2,title:'第二集',body:'第二集保持不变'}],model:'glm',onFocusEpisode:setFocus,onApplyCandidates:()=>{}}} onApplyRewrite={c=>{if(c.originalBody!==body)return false;f.backups.push(body);localStorage.setItem('test-saved-body',c.rewrittenBody);setBody(c.rewrittenBody);f.writes.push(c);return true;}} project={{context:{seriesTitle:'隔离长安先知簿',episodeIndex:focus,episodeTitle:focus===1?'文书库':'第二集',stage:'outline',videoModel:'未选择',writerConfirmed:true,episodeBody:focus===1?body:'第二集保持不变',assetSummary:'',shotSummary:'',blockers:[]},issues:[],contextNotes:[],selectionLabel:'第二集'}}/>}createRoot(document.getElementById('root')).render(<App/>);`},bundle:true,write:false,platform:'browser',format:'iife',jsx:'automatic',loader:{'.css':'empty','.woff':'dataurl','.woff2':'dataurl'},alias:{'@':path.resolve('client/src'),'@shared':path.resolve('shared')},define:{'process.env.NODE_ENV':'"test"','import.meta.env':'{}'},plugins:[{name:'explicit-service-boundaries',setup(b){b.onResolve({filter:/\.\/CreativeVoicePanel$/},()=>({path:'voice',namespace:'fixture'}));b.onResolve({filter:/^@\/lib\/manhuaAdvisorStream$/},()=>({path:'stream',namespace:'fixture'}));b.onResolve({filter:/^@\/lib\/trpc$/},()=>({path:'trpc',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},a=>({loader:'tsx',resolveDir:process.cwd(),contents:a.path==='voice'?`export function CreativeVoicePanel(p){globalThis.fixture.production=p.onProductionAction;return <div>隔离语音入口</div>}`:a.path==='trpc'?`export const trpc={mvAnalysis:{getManhuaAdvisorQuota:{useQuery:()=>({data:{remaining:5,price:12,exempt:false},refetch:async()=>({})})}}};`:`export async function streamManhuaAdvisor(input){const f=globalThis.fixture;f.requests.push(input);return {answer:JSON.stringify({kind:'template-rewrite',body:f.revised,endHook:'门后有人',changes:['天光与架间阴影形成反差']}),remainingFreeToday:4,paidUnitCredits:12,creditsCharged:0,paidThisTurn:false};}` }));}}]});
 const browser=await puppeteer.launch({headless:true,executablePath:process.env.PUPPETEER_EXECUTABLE_PATH || (existsSync('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome') ? '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' : undefined),args:['--no-sandbox']});
 try {const page=await browser.newPage();page.setDefaultTimeout(6000);page.on('pageerror',e=>console.error('browser error',e instanceof Error ? e.message : String(e)));await page.setRequestInterception(true);page.on('request',r=>r.isNavigationRequest()?void r.respond({status:200,contentType:'text/html',body:'<div id="root"></div>'}):void r.abort());await page.goto('http://localhost:41839/');await page.addScriptTag({content:result.outputFiles[0].text});await page.waitForFunction(()=>!!(globalThis as any).fixture?.production);
 console.log('voice handler ready');const receipt=await page.evaluate(()=>(globalThis as any).fixture.production({action:'prepareEpisode',episode:1,question:'你把这个部分推送给这个创作顾问, 让他修改一下。第一集的内容。'},new AbortController().signal));expect(JSON.parse(receipt).status).toBe('candidate_ready');
 const req=await page.evaluate(()=>(globalThis as any).fixture.requests[0]);expect(req.rawQuestion).toMatch(/^【模板改写建议】/);expect(req.manhuaContext.episodeIndex).toBe(1);expect(req.manhuaContext.episodeBody).toContain('沈昀');expect(req.manhuaContext.worldTarget).toBeUndefined();expect(req.manhuaContext.previsEdit).toBeUndefined();expect(await page.evaluate(()=>(globalThis as any).fixture.writes.length)).toBe(0);
 await page.waitForSelector('[aria-label="优化后整集正文"]');await page.evaluate(()=>{window.confirm=()=>false;});expect(await page.evaluate(()=>(globalThis as any).fixture.production({action:'applyEpisode',episode:1},new AbortController().signal))).toContain('取消');expect(await page.evaluate(()=>(globalThis as any).fixture.writes.length)).toBe(0);
 await page.evaluate(()=>{window.confirm=()=>true;});expect(await page.evaluate(()=>(globalThis as any).fixture.production({action:'applyEpisode',episode:1},new AbortController().signal))).toContain('已写回');expect(await page.evaluate(()=>localStorage.getItem('test-saved-body'))).toContain('天光落在纸页上');expect(await page.evaluate(()=>(globalThis as any).fixture.backups.length)).toBe(1);
 }finally{await browser.close();}
},30000);
