import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {neon} from '@neondatabase/serverless';
import {downloadGcsObject,uploadBufferToGcs} from '/Users/tangenjie/Documents/Codex/2026-10-06/task-5/manhua-effects-1007/server/services/gcs';
import {refreshManhuaAdvisorKnowledge,resolveManhuaAdvisorKnowledgeTemplate} from '/Users/tangenjie/Documents/Codex/2026-10-06/task-5/manhua-effects-1007/server/services/manhuaAdvisorKnowledge';
assert.equal(process.env.FLY_MACHINE_ID,'7812595b294778');assert(process.cwd().startsWith('/tmp/pr1675-isolated-'));
const base='post-prod/isolated-pr1675/probe-evidence/20261007T081759-9692764c/';const bucket='gs://mv-studio-pro-vertex-video-temp/';
let prior=false;for(const f of ['vfx/result.json','cloth/result.json','explode/result.json','label/failure.json','label-r2/result.json','transition/result.json','knowledge/result.json','knowledge/failure.json']) {try {const {buffer}=await downloadGcsObject({gcsUri:bucket+base+f}); console.log('ARTIFACT:'+JSON.stringify({name:f,data:buffer.toString('base64')}));if(f==='knowledge/result.json')prior=JSON.parse(buffer.toString()).status==='passed';}catch(e){if(!String(e).includes('gcs_download_failed:404:'))throw new Error('Evidence lookup failed');console.log(JSON.stringify({missing:f}));}}
if(prior){console.log('EXISTING_KNOWLEDGE_PASS_REUSED');process.exit(0);}
const sql=neon(process.env.DATABASE_URL!);const pending=await sql`SELECT id,type,status FROM jobs WHERE status in ('queued','running')`;assert.equal(pending.length,0);
await mkdir('evidence/knowledge-r2',{recursive:true});const receipts:any[]=[];
const save=async(name:string,value:unknown)=>{const buffer=Buffer.from(JSON.stringify(value));await writeFile('evidence/knowledge-r2/'+name,buffer,{flag:'wx'});const saved=await uploadBufferToGcs({objectName:base+'knowledge-r2/'+name,buffer,contentType:'application/json'});const read=await downloadGcsObject({gcsUri:saved.gcsUri});const sha=(b:Buffer)=>createHash('sha256').update(b).digest('hex');assert.equal(sha(read.buffer),sha(buffer));receipts.push({name,gcsUri:saved.gcsUri,bytes:buffer.length,sha256:sha(buffer),readBackVerified:true});return saved.gcsUri;};
await save('preflight.json',{at:new Date().toISOString(),machine:process.env.FLY_MACHINE_ID,pending,source:JSON.parse(await readFile('source-manifest-r4.json','utf8')),boundary:'Interrupted prior cold scan; fresh process after idle stop. Read-only public catalog, no models or jobs.'});
try {const cold=await refreshManhuaAdvisorKnowledge();await save('knowledge-cold.json',cold);assert.equal(cold.status,'ready',cold.error);const warm=await refreshManhuaAdvisorKnowledge();await save('knowledge-warm.json',warm);assert.equal(warm.status,'ready',warm.error);assert.equal(warm.changes?.downloadedCards,0);assert.equal(warm.snapshot?.revision,cold.snapshot?.revision);const selected=cold.snapshot?.templates[0];let resolution:any;
if(selected){const r=await resolveManhuaAdvisorKnowledgeTemplate(selected.publicId);assert(!('error' in r));assert.equal(r.resolution,'indexed');resolution={publicId:r.appliedTemplate.publicId,resolution:r.resolution};}
const result={status:'passed',templateCount:cold.snapshot?.templates.length,directorCount:cold.snapshot?.directors.length,coldDownloads:cold.changes?.downloadedCards,warmDownloads:warm.changes?.downloadedCards,selectedResolution:resolution,modelCalls:0,receipts};const gcsUri=await save('result.json',result);console.log(JSON.stringify({event:'passed',phase:'knowledge-r2',gcsUri,...result}));
}catch(e){const failure={status:'failed',error:e instanceof Error?e.message:String(e),receipts};const gcsUri=await save('failure.json',failure);console.log(JSON.stringify({event:'failed',gcsUri,...failure}));process.exitCode=1;}
