/**
 * Audio Watermark Service
 * Generates a "MVStudioPro.com" voice intro using fal.ai Kokoro TTS
 * and provides the audio URL for frontend to prepend before playing songs.
 */
import { fal } from "@fal-ai/client";
import { storagePut } from "./storage";

// Cache the generated watermark audio URL to avoid regenerating
let cachedWatermarkUrl: string | null = null;

const WATERMARK_TEXT = "This music is generated by MV Studio Pro dot com";

/**
 * Generate or retrieve the cached watermark audio URL
 */
export async function getWatermarkAudioUrl(): Promise<string> {
  if (cachedWatermarkUrl) {
    return cachedWatermarkUrl;
  }

  fal.config({ credentials: process.env.FAL_API_KEY });

  const result = await fal.run("fal-ai/kokoro", {
    input: {
      text: WATERMARK_TEXT,
      voice: "af_heart",
    },
  }) as any;

  const audioUrl = result?.data?.audio?.url || result?.audio?.url;
  if (!audioUrl) {
    throw new Error("Failed to generate watermark audio");
  }

  // Download and re-upload to our S3 for persistence
  const response = await fetch(audioUrl);
  if (!response.ok) {
    throw new Error(`Failed to download watermark audio: ${response.status}`);
  }
  const buffer = Buffer.from(await response.arrayBuffer());
  const key = `watermarks/audio/mvstudiopro-intro-${Date.now()}.wav`;
  const { url } = await storagePut(key, buffer, "audio/wav");

  cachedWatermarkUrl = url;
  return url;
}
