import type { ManhuaVfxEffect } from "@shared/manhuaVfx";

export type VfxSceneOption = { jobId: string; scopeId: string; clipId: string; label: string; durationSec: number };
type Field = { key: string; label: string; min: number; max: number; step?: number };
const inputClass = "mt-1 w-full rounded border border-white/15 bg-black/30 px-2 py-1.5 text-xs text-white";
export function ManhuaVfxEffectParameters({ effect, scenes, onChange }: { effect: ManhuaVfxEffect; scenes: VfxSceneOption[]; onChange: (patch: Partial<ManhuaVfxEffect>) => void }) {
  const numbers = (group: "roi" | "liquid" | "ghost" | "wall" | "bullet" | "wave" | "blast" | "mirror" | "paper" | "prop" | "city" | "world", fields: Field[]) => <div className="grid grid-cols-2 gap-2">{fields.map(field => <label key={field.key} className="text-[11px] text-white/60">{field.label}<input aria-label={`${group}-${field.key}`} type="number" className={inputClass} min={field.min} max={field.max} step={field.step ?? .01} value={Number((effect[group] as unknown as Record<string, unknown>)?.[field.key])} onChange={event => onChange({ [group]: { ...effect[group], [field.key]: Number(event.target.value) } })} /></label>)}</div>;
  return <div className="space-y-2 text-[11px] text-white/60">
    {effect.world ? <><p>选择与原片对应的已保存三维动画。人物按原场景时间继续活动，碎片独立定格，前后遮挡由同场三维渲染计算。静态场景或定格窗内人物没有动作时会明确报错。人物沿原动画活动，请调整道具位置避免穿模；此处不自动生成避让动作。</p><label>人物动画场景<select aria-label="world-scene" className={inputClass} value={effect.world.sceneJobId} onChange={event => { const scene = scenes.find(scene => scene.jobId === event.target.value); if (scene) onChange({ world: { ...effect.world!, sceneJobId: scene.jobId, sceneScopeId: scene.scopeId, clipId: scene.clipId, sourceStartSec: 0 } }); }}><option value="">选择当前作品已完成的三维动画</option>{scenes.map(scene => <option key={scene.jobId} value={scene.jobId}>{scene.label}</option>)}</select></label>{!scenes.length ? <p className="text-amber-200">当前没有已保存的三维场景，请先保存本段人物动画。原片模式可保留人物运动，但不提供三维前后穿行。</p> : null}<label>碎裂道具<select aria-label="world-propKind" className={inputClass} value={effect.world.propKind} onChange={event => onChange({ world: { ...effect.world!, propKind: event.target.value as "cup_fracture" | "fruit_stall_fracture" }, prop: { ...effect.prop!, staggerSec: event.target.value === "cup_fracture" ? 0 : .1 } })}><option value="fruit_stall_fracture">水果摊连锁碎裂</option><option value="cup_fracture">咖啡杯碎裂</option></select></label>{numbers("world", [{ key: "sourceStartSec", label: "人物动画起始秒", min: 0, max: scenes.find(scene => scene.jobId === effect.world!.sceneJobId)?.durationSec ?? 30, step: .05 }, { key: "size", label: "道具尺寸倍数", min: .05, max: 4 }, { key: "yawDeg", label: "道具朝向角度", min: -180, max: 180, step: 1 }])}<div className="grid grid-cols-3 gap-2">{([0,1,2] as const).map(axis => <label key={axis}>道具位置{"XYZ"[axis]}（米）<input aria-label={`world-position-${axis}`} className={inputClass} type="number" min={-100} max={100} step={.1} value={effect.world!.position[axis]} onChange={event => { const position: [number,number,number] = [...effect.world!.position]; position[axis] = Number(event.target.value); onChange({ world: { ...effect.world!, position } }); }} /></label>)}</div></> : null}
    {effect.city ? <><p>真实三维街区，用透视相机拍摄地面与楼群沿铰链向上翻折。此时窗显示程序街区，原声保留；不从原片重建巴黎，也不把原片人物带入新场景。与其他效果错开时窗。</p>{numbers("city", [{ key: "blocks", label: "每侧楼群数量", min: 2, max: 6, step: 1 }, { key: "foldDeg", label: "翻折角度", min: 30, max: 150, step: 1 }, { key: "foldStartSec", label: "窗内开始翻折秒", min: 0, max: effect.durationSec, step: .05 }, { key: "foldEndSec", label: "窗内完成翻折秒", min: 0, max: effect.durationSec, step: .05 }, { key: "streetWidth", label: "街道宽度（米）", min: 4, max: 12 }, { key: "buildingHeight", label: "楼群基准高度（米）", min: 5, max: 20 }, { key: "lensMm", label: "透视相机焦距", min: 24, max: 65, step: 1 }])}</> : null}
    {effect.prop ? <><p>{effect.world ? "道具在人物三维场景中完整出现，再破裂并定格；原有人物动画持续播放。" : "真实三维道具先完整出现，再破裂飞散并定格；原片人物保持运动。新增道具叠加不自动删除原片物体，也不自动处理人物遮挡。"}</p>{numbers("prop", [{ key: "impactSec", label: "窗内起爆秒", min: 0, max: effect.durationSec, step: .05 }, { key: "spread", label: "碎片散射力度", min: .1, max: 3 }, { key: "slowMotion", label: "爆发后的运动速度", min: .03, max: 1 }, { key: "gravity", label: "碎片下坠", min: 0, max: 6 }, { key: "holdStartSec", label: "窗内开始定格秒", min: 0, max: effect.durationSec, step: .05 }, { key: "holdDurationSec", label: "定格持续秒", min: .1, max: 10, step: .1 }, ...((effect.world?.propKind || effect.kind) === "fruit_stall_fracture" ? [{ key: "staggerSec", label: "相邻爆点间隔秒", min: 0, max: .5, step: .05 }] : [])])}<p>爆发先快后慢，再定格，定格结束后续运动。定格只影响道具，人物和声音保持原速；果摊从左到右分四组起爆。</p></> : null}
    {effect.mirror ? <><p>递归缩小并交替镜像原片区域，形成镜面纵深。不会重建三维走廊或反射人物背面。</p>{numbers("mirror", [{ key: "layers", label: "镜层数量", min: 2, max: 8, step: 1 }, { key: "shrink", label: "逐层缩小比例", min: .45, max: .85 }, { key: "drift", label: "纵深漂移", min: 0, max: .08, step: .005 }])}</> : null}
    {effect.paper ? <><p>程序纸页在画面上悬浮、翻转和轻微漂移；不改变原片角色重力或计算人物遮挡。</p>{numbers("paper", [{ key: "count", label: "纸页数量", min: 6, max: 64, step: 1 }, { key: "size", label: "纸页大小（画面高比例）", min: .015, max: .12, step: .005 }, { key: "drift", label: "漂移速度", min: 0, max: .6 }, { key: "flutter", label: "翻动速度", min: 0, max: 4, step: .1 }, { key: "spread", label: "分布范围", min: .1, max: 1.5 }])}</> : null}
    {effect.wave ? <><p>挂点是弹道起点，角度0向右、90向下；轨迹移动整条弹道。直接折射原片，圈数、尾迹和折射强度可调。</p>{numbers("wave", [{ key: "angleDeg", label: "方向角度", min: -360, max: 360, step: 1 }, { key: "reach", label: "前进距离（画面高度）", min: .05, max: 1.8 }, { key: "radius", label: "波纹半径", min: .02, max: .22, step: .005 }, { key: "rings", label: "波纹圈数", min: 2, max: 10, step: 1 }, { key: "trailSec", label: "尾迹秒数", min: .03, max: .6 }, { key: "refraction", label: "折射强度", min: .001, max: .04, step: .001 }, { key: "glow", label: "边缘微光", min: 0, max: 1 }])}</> : null}
    {effect.blast ? <><p>方向角度0向右、90向下。程序火团、火花、碎片与烟尘叠加，不会自动移除原片物体。</p>{numbers("blast", [{ key: "angleDeg", label: "爆破方向", min: -360, max: 360, step: 1 }, { key: "spreadDeg", label: "扩散角度", min: 5, max: 160, step: 1 }, { key: "reach", label: "喷射距离（画面高度）", min: .05, max: 2 }, { key: "particles", label: "颗粒数量", min: 16, max: 144, step: 1 }, { key: "gravity", label: "碎片下坠", min: 0, max: 6 }, { key: "smoke", label: "烟尘量", min: 0, max: 1 }, { key: "ignitionSec", label: "窗内起爆秒", min: 0, max: effect.durationSec, step: .05 }])}</> : null}
    {effect.roi ? <><p>手动区域随挂点与轨迹移动；形状内会保留背景，不做自动人物抠像。</p><label>区域形状<select aria-label="roi-shape" className={inputClass} value={effect.roi.shape} onChange={event => onChange({ roi: { ...effect.roi!, shape: event.target.value as "ellipse" | "rectangle" } })}><option value="ellipse">椭圆</option><option value="rectangle">矩形</option></select></label>{numbers("roi", [{ key: "width", label: "区域宽度", min: .01, max: 1 }, { key: "height", label: "区域高度", min: .01, max: 1 }, { key: "feather", label: "边缘羽化", min: 0, max: .5 }])}</> : null}
    {effect.liquid ? <><p>变形当前原片像素并混入局部镜像，不是三维反射。</p>{numbers("liquid", [{ key: "amplitude", label: "波动幅度", min: 0, max: .08, step: .001 }, { key: "frequency", label: "波纹密度", min: .5, max: 12, step: .1 }, { key: "speed", label: "波动速度", min: 0, max: 8, step: .1 }, { key: "reflection", label: "镜像混合", min: 0, max: 1 }])}</> : null}
    {effect.ghost ? <><p>取真实历史帧；拖影数量、时间间隔与位移可变，当前区域保留。</p>{numbers("ghost", [{ key: "copies", label: "残影数量", min: 1, max: 6, step: 1 }, { key: "spacingSec", label: "间隔秒数", min: 1 / 60, max: .2 }, { key: "decay", label: "保留强度", min: .1, max: .95 }, { key: "offsetX", label: "横向位移", min: -.25, max: .25 }, { key: "offsetY", label: "纵向位移", min: -.25, max: .25 }])}</> : null}
    {effect.wall ? <><p>真实程序碎片墙体，可调撞击位置与散射；不自动识别或删除原片墙体。</p>{numbers("wall", [{ key: "columns", label: "横向分块", min: 2, max: 10, step: 1 }, { key: "rows", label: "纵向分块", min: 2, max: 10, step: 1 }, { key: "impactSec", label: "窗内撞击秒", min: 0, max: effect.durationSec, step: .05 }, { key: "spread", label: "散射力度", min: 0, max: 3 }, { key: "gravity", label: "下坠力度", min: 0, max: 6 }, { key: "depth", label: "透视深度", min: .2, max: 4 }])}<div className="grid grid-cols-2 gap-2">{(["x", "y"] as const).map(axis => <label key={axis}>撞击{axis === "x" ? "横向" : "纵向"}位置<input aria-label={`wall-contact-${axis}`} className={inputClass} type="number" min={0} max={1} step={.01} value={effect.wall!.contact[axis]} onChange={event => onChange({ wall: { ...effect.wall!, contact: { ...effect.wall!.contact, [axis]: Number(event.target.value) } } })} /></label>)}</div></> : null}
    {effect.bullet ? <><p>冻结实际三维场景姿态，用透视相机环绕，默认360度；原声保留，时窗与其他效果分开。</p><label>三维场景<select aria-label="bullet-scene" className={inputClass} value={effect.bullet.sceneJobId} onChange={event => { const scene = scenes.find(scene => scene.jobId === event.target.value); if (scene) onChange({ bullet: { ...effect.bullet!, sceneJobId: scene.jobId, sceneScopeId: scene.scopeId, clipId: scene.clipId, freezeSec: 0 } }); }}><option value="">选择当前作品已完成的三维预演</option>{scenes.map(scene => <option key={scene.jobId} value={scene.jobId}>{scene.label}</option>)}</select></label>{!scenes.length ? <p className="text-amber-200">当前没有已完成的三维场景，请先在本段三维预演中保存真实场景。二维原片无法替代。</p> : null}{numbers("bullet", [{ key: "freezeSec", label: "场景冻结秒位", min: 0, max: scenes.find(scene => scene.jobId === effect.bullet!.sceneJobId)?.durationSec ?? 30, step: .05 }, { key: "startAngleDeg", label: "起始角度", min: -360, max: 360, step: 1 }, { key: "sweepDeg", label: "环绕角度", min: -360, max: 360, step: 1 }, { key: "radius", label: "环绕半径（米）", min: .5, max: 30, step: .1 }, { key: "height", label: "相对目标高度（米）", min: -10, max: 30, step: .1 }, { key: "lensMm", label: "焦距（毫米）", min: 18, max: 100, step: 1 }])}<div className="grid grid-cols-3 gap-2">{([0, 1, 2] as const).map(axis => <label key={axis}>目标{"XYZ"[axis]}<input aria-label={`bullet-target-${axis}`} className={inputClass} type="number" min={-100} max={100} step={.1} value={effect.bullet!.target[axis]} onChange={event => { const target: [number, number, number] = [...effect.bullet!.target]; target[axis] = Number(event.target.value); onChange({ bullet: { ...effect.bullet!, target } }); }} /></label>)}</div></> : null}
  </div>;
}
