import type { WorkflowTask } from "./types/workflow";
import { saveWorkflow, updateWorkflow, getWorkflow } from "./store/workflowStore";
import { routeModel } from "../router/modelRouter";

export async function startWorkflow(task: WorkflowTask) {
  saveWorkflow(task);

  try {
    if (task.inputType === "script") {
      return await runScriptWorkflow(task.workflowId);
    }

    if (task.inputType === "image") {
      return await runImageWorkflow(task.workflowId);
    }

    throw new Error("unknown workflow inputType");
  } catch (error) {
    updateWorkflow(task.workflowId, {
      status: "failed",
      currentStep: "error",
    });
    throw error;
  }
}

async function runScriptWorkflow(workflowId: string) {
  const task = getWorkflow(workflowId);
  if (!task) throw new Error("workflow not found");

  updateWorkflow(workflowId, {
    status: "running",
    currentStep: "script",
  });

  const scriptRoute = routeModel("script");

  updateWorkflow(workflowId, {
    currentStep: "storyboard",
    outputs: {
      script: `generated by ${scriptRoute.provider}/${scriptRoute.model}`,
      storyboard: [
        {
          sceneIndex: 1,
          scenePrompt: task.payload?.prompt || "",
          duration: 5,
          camera: "medium",
          mood: "cinematic",
        },
      ],
    },
  });

  const videoRoute = routeModel("video");

  updateWorkflow(workflowId, {
    currentStep: "video",
    outputs: {
      videoUrl: `mock://${videoRoute.provider}/${videoRoute.model}`,
    },
  });

  updateWorkflow(workflowId, {
    status: "done",
    currentStep: "done",
  });

  return getWorkflow(workflowId);
}

async function runImageWorkflow(workflowId: string) {
  const task = getWorkflow(workflowId);
  if (!task) throw new Error("workflow not found");

  const imageUrl = task.payload?.imageUrl;
  if (!imageUrl || typeof imageUrl !== "string") {
    updateWorkflow(workflowId, {
      status: "failed",
      currentStep: "error",
    });
    throw new Error("missing payload.imageUrl");
  }

  updateWorkflow(workflowId, {
    status: "running",
    currentStep: "video",
  });

  const videoRoute = routeModel("video");
  const encodedImageUrl = encodeURIComponent(imageUrl);

  updateWorkflow(workflowId, {
    outputs: {
      videoUrl: `mock://${videoRoute.provider}/${videoRoute.model}?imageUrl=${encodedImageUrl}`,
    },
  });

  updateWorkflow(workflowId, {
    status: "done",
    currentStep: "done",
  });

  return getWorkflow(workflowId);
}
