import type { WorkflowTask } from "./types/workflow";
import { saveWorkflow, updateWorkflow } from "./store/workflowStore";
import { routeModel } from "../router/router";

export async function startWorkflow(task: WorkflowTask) {
  saveWorkflow(task);

  try {
    if (task.inputType === "script") {
      await runScriptWorkflow(task);
      return;
    }

    if (task.inputType === "image") {
      await runImageWorkflow(task);
      return;
    }

    throw new Error("unknown workflow inputType");
  } catch (error) {
    updateWorkflow(task.workflowId, {
      status: "failed",
      currentStep: "error",
    });
    throw error;
  }
}

async function runScriptWorkflow(task: WorkflowTask) {
  updateWorkflow(task.workflowId, {
    status: "running",
    currentStep: "script",
  });

  const scriptRoute = routeModel("script", {
    workflowType: "script-to-video",
    inputType: "script",
  });

  updateWorkflow(task.workflowId, {
    currentStep: "storyboard",
    outputs: {
      ...task.outputs,
      script: `generated by ${scriptRoute.provider}/${scriptRoute.model}`,
      storyboard: [
        {
          sceneIndex: 1,
          scenePrompt: task.payload?.prompt || "",
          duration: 5,
          camera: "medium",
          mood: "cinematic",
        },
      ],
    },
  });

  const videoRoute = routeModel("video", {
    workflowType: "script-to-video",
    inputType: "script",
  });

  updateWorkflow(task.workflowId, {
    currentStep: "video",
    outputs: {
      ...task.outputs,
      videoUrl: `mock://${videoRoute.provider}/${videoRoute.model}`,
    },
  });

  updateWorkflow(task.workflowId, {
    status: "done",
    currentStep: "done",
  });
}

async function runImageWorkflow(task: WorkflowTask) {
  updateWorkflow(task.workflowId, {
    status: "running",
    currentStep: "video",
  });

  const videoRoute = routeModel("video", {
    workflowType: "image-to-video",
    inputType: "image",
  });

  updateWorkflow(task.workflowId, {
    outputs: {
      ...task.outputs,
      videoUrl: `mock://${videoRoute.provider}/${videoRoute.model}`,
    },
  });

  updateWorkflow(task.workflowId, {
    status: "done",
    currentStep: "done",
  });
}
