/**
 * 平台官方活动策展种子。
 * 小红书条目主要来自 `~/Downloads/2026Jul13/ac.mp4`（创作者中心 → 创作灵感 → 活动）
 * 超高密度抽帧 OCR：`ac-frames-dense/`（fps=4，约262帧，片长~66s）。
 * 其他平台保留扶持计划同构结构。
 */

export type OfficialCampaignKind = "topic_challenge" | "traffic_support" | "festival";

export type OfficialCampaignCategory =
  | "summer_lifestyle"
  | "city_walk"
  | "fmcg_goods"
  | "wellness_sport"
  | "culture_reading"
  | "aesthetics_design"
  | "food_local"
  | "music_art"
  | "gaming_ip"
  | "creator_incentive"
  | "family_life"
  | "tech_digital";

export type OfficialCampaignLaneHint = "fmcg" | "forensic" | "crossover" | "contrast" | "default";

export type OfficialCampaignSeed = {
  id: string;
  platform: "xiaohongshu" | "douyin" | "bilibili" | "kuaishou" | "toutiao";
  name: string;
  kind: OfficialCampaignKind;
  category: OfficialCampaignCategory;
  featured: boolean;
  personaFit: string;
  topicHooks: string[];
  laneHints: OfficialCampaignLaneHint[];
  summary: string;
  /** 活动窗（截图所见，月-日） */
  windowHint?: string;
  status: "active" | "watch" | "expired";
  sourceNote: string;
  reviewedAt: string;
};

/**
 * 小红书：ac.mp4 活动中心精选。
 * featured=true → 与康养×古典审美×城市生活/畅销品科普方向可结合，优先进报表与选题。
 */
export const XHS_OFFICIAL_CAMPAIGN_SEEDS: OfficialCampaignSeed[] = [
  // —— 与人设强契合（精选）——
  {
    id: "xhs-room-for-life-2026",
    platform: "xiaohongshu",
    name: "有余地的生活",
    kind: "topic_challenge",
    category: "summer_lifestyle",
    featured: true,
    personaFit: "高净值康养哲学主入口：留白节律、展后松弛、杂志书气质。",
    topicHooks: [
      "有余地的生活｜看完上博东馆，把晚上两小时留给不回复的自己",
      "有余地的生活：周五只排一场展+一顿松弛晚餐",
    ],
    laneHints: ["default", "contrast"],
    summary: "小红书第11本杂志书主题：分享有余地的生活指南。",
    windowHint: "07-08至09-30",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-busy-travel-2026",
    platform: "xiaohongshu",
    name: "sorry我忙着旅游呢",
    kind: "topic_challenge",
    category: "city_walk",
    featured: true,
    personaFit: "暑期城市行程：馆/市集/漫步清单笔记（对标 m1 合集密度）。",
    topicHooks: [
      "sorry我忙着旅游呢｜上海七月不可错过重磅展合集（大部分免费）",
      "旅行热门范式：人民广场馆→东馆双展怎么走不赶场",
    ],
    laneHints: ["default", "crossover"],
    summary: "旅行热门范式速递：暑期出行/Citywalk 内容加权。",
    windowHint: "07-12至07-19（短窗，报表须标时效）",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-howto-main-character-2026",
    platform: "xiaohongshu",
    name: "howto拍出主角感",
    kind: "topic_challenge",
    category: "aesthetics_design",
    featured: true,
    personaFit: "看展/场馆出片：古典容器+主角感构图，不做创作 SOP 格。",
    topicHooks: [
      "howto拍出主角感｜博物馆侧光位，少色块多留白",
      "展厅里的主角感：一张能停滑的封面怎么立",
    ],
    laneHints: ["default", "contrast"],
    summary: "分享放松自信的拍照心得，赢流量向活动。",
    windowHint: "07-08起",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-howto-home-cool-2026",
    platform: "xiaohongshu",
    name: "howto给家降二度",
    kind: "topic_challenge",
    category: "summer_lifestyle",
    featured: true,
    personaFit: "夏日清凉：可叠冰饮/家居好物翻标算账，勿恐吓。",
    topicHooks: [
      "howto给家降二度｜先别狂开空调：三口清凉账怎么算",
      "降温教程：室内展+家居清凉，少靠冰饮硬顶",
    ],
    laneHints: ["fmcg", "default"],
    summary: "分享降温教程赢大额流量扶持。",
    windowHint: "07-06至08-15",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-frozen-sect-2026",
    platform: "xiaohongshu",
    name: "冻门永存",
    kind: "topic_challenge",
    category: "fmcg_goods",
    featured: true,
    personaFit: "冰品/冻饮痛点槽点科普（ice 弧）；权威一句强制落正文。",
    topicHooks: [
      "冻门永存｜这款雪糕糖一日上限占比你算过吗",
      "冻门笔记：同柜两支冰，差别可能在营养成分表",
    ],
    laneHints: ["fmcg", "forensic"],
    summary: "美食门派·冻门：发冻门笔记赢流量。",
    windowHint: "07-06至08-31",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-food-master-2026",
    platform: "xiaohongshu",
    name: "美食掌门人",
    kind: "topic_challenge",
    category: "food_local",
    featured: true,
    personaFit: "市集/展后一餐；可叠轻科普，忌诊疗承诺。",
    topicHooks: ["美食掌门人｜东馆市集摊位：好看之外先看配料前三名"],
    laneHints: ["fmcg", "default"],
    summary: "加入美食门派赢限量周边。",
    windowHint: "07-06至08-31",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-summer-stronger-2026",
    platform: "xiaohongshu",
    name: "一个夏天能变多强",
    kind: "topic_challenge",
    category: "wellness_sport",
    featured: true,
    personaFit: "暑期身体账/可重复小顺序；叠身体活动指南一句。",
    topicHooks: [
      "一个夏天能变多强｜不靠狠练：下班十分钟活动账",
      "暑期打卡：看完马王堆再走路，把活动写进日程",
    ],
    laneHints: ["default", "forensic"],
    summary: "参与活动打卡赢好礼（暑期变强主题）。",
    windowHint: "06-26至08-01",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-howto-cortisol-2026",
    platform: "xiaohongshu",
    name: "howto稳住皮质醇",
    kind: "topic_challenge",
    category: "wellness_sport",
    featured: true,
    personaFit: "高压生活节律主战场；强监管优化表达，禁诊疗恐吓。",
    topicHooks: [
      "howto稳住皮质醇｜会议从不停时，先保命的三个身体动作",
      "在这里我先分享一些：把『余地』写进会后十分钟",
    ],
    laneHints: ["forensic", "default"],
    summary: "howto 系列：稳住压力荷尔蒙相关生活教程（OCR 见 howto稳住皮质*）。",
    windowHint: "06-24起",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-treasure-bookstore-2026",
    platform: "xiaohongshu",
    name: "送你的宝藏书店上书博",
    kind: "topic_challenge",
    category: "culture_reading",
    featured: true,
    personaFit: "文化容器：书店/展签一句→当代生活对照，禁读论文口播。",
    topicHooks: [
      "送你的宝藏书店上书博｜三本不讲鸡汤的暑期书，读完只改一件日常",
    ],
    laneHints: ["crossover", "default"],
    summary: "第34届书博相关：推荐宝藏书店/书单。",
    windowHint: "06-26至07-31",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-sing-contrary-2026",
    platform: "xiaohongshu",
    name: "唱唱反调",
    kind: "topic_challenge",
    category: "culture_reading",
    featured: true,
    personaFit: "对社会文化现象发声：反差切口，仍须生活画面。",
    topicHooks: ["唱唱反调｜别再把『自律』当成唯一正确答案"],
    laneHints: ["contrast", "default"],
    summary: "分享你对社会文化现象的见解。",
    windowHint: "06-29至08-09",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-earphone-half-2026",
    platform: "xiaohongshu",
    name: "耳机分你一半",
    kind: "topic_challenge",
    category: "music_art",
    featured: true,
    personaFit: "爵士/音乐生活切片：听觉节律。",
    topicHooks: ["耳机分你一半｜听完这段为什么更想躺？先别苛责自己"],
    laneHints: ["default", "crossover"],
    summary: "发布音乐分享笔记得好礼。",
    windowHint: "06-26至08-31",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-french-life-2026",
    platform: "xiaohongshu",
    name: "我的法式生活",
    kind: "topic_challenge",
    category: "aesthetics_design",
    featured: true,
    personaFit: "审美容器：法式松弛≠堆单品；可对接古典美学日常。",
    topicHooks: ["我的法式生活｜看展日少色块，镜头更干净"],
    laneHints: ["default", "contrast"],
    summary: "分享你的法式生活指南。",
    windowHint: "06-05至09-30",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-outdoor-explorer-2026",
    platform: "xiaohongshu",
    name: "户外探索者图鉴",
    kind: "topic_challenge",
    category: "wellness_sport",
    featured: true,
    personaFit: "户外/攀岩/行走：身体活动生活化。",
    topicHooks: ["户外探索者图鉴｜100条线路之前，先搞定可重复的十分钟走"],
    laneHints: ["default"],
    summary: "发视频分享户外探险故事。",
    windowHint: "06-05起",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-design-openmic-2026",
    platform: "xiaohongshu",
    name: "小红书设计开放麦",
    kind: "topic_challenge",
    category: "aesthetics_design",
    featured: true,
    personaFit: "设计/版式审美发言：图文笔记页角色可蹭。",
    topicHooks: ["小红书设计开放麦｜封面只讲一个结果：人群+痛点+钉子"],
    laneHints: ["default"],
    summary: "全体设计师请发言。",
    windowHint: "07-10至08-31",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-online-grad-show-2026",
    platform: "xiaohongshu",
    name: "小红书线上毕业展",
    kind: "topic_challenge",
    category: "music_art",
    featured: true,
    personaFit: "艺术/毕业展：可对接美术馆合集笔记。",
    topicHooks: ["小红书线上毕业展｜把展签一句翻译成今晚能用的节律判断"],
    laneHints: ["crossover", "default"],
    summary: "见证艺术毕业生发光的时刻。",
    windowHint: "05-20至07-31",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-admission-letter-2026",
    platform: "xiaohongshu",
    name: "用录取通知书打开大学",
    kind: "topic_challenge",
    category: "summer_lifestyle",
    featured: true,
    personaFit: "暑期人生节点：节律/压力过渡（新人向可改写）。",
    topicHooks: ["用录取通知书打开大学｜开学前先学会给生活留余地"],
    laneHints: ["default"],
    summary: "发布笔记赢流量券和周边（录取进行时）。",
    windowHint: "07-11至07-31",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-night-school-2026",
    platform: "xiaohongshu",
    name: "跟雅琪一起0元上夜校",
    kind: "topic_challenge",
    category: "culture_reading",
    featured: true,
    personaFit: "晚间学习计划：轻知识图文，不做课堂挂图。",
    topicHooks: ["0元夜校｜今晚只学一件：翻标看懂添加糖占比"],
    laneHints: ["fmcg", "default"],
    summary: "开启你的晚间学习计划。",
    windowHint: "07-07至09-30",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-hyrox-hz-2026",
    platform: "xiaohongshu",
    name: "HYROX杭州站",
    kind: "topic_challenge",
    category: "wellness_sport",
    featured: true,
    personaFit: "赛事体能故事：可迁移为高强度后的恢复节律（非诊疗）。",
    topicHooks: ["HYROX杭州站｜赛后恢复不是躺平：先做可重复的小顺序"],
    laneHints: ["default", "forensic"],
    summary: "分享 HYROX 故事。",
    windowHint: "06-29至07-30",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-howto-homophone-dish-2026",
    platform: "xiaohongshu",
    name: "howto做出谐音梗",
    kind: "topic_challenge",
    category: "food_local",
    featured: false,
    personaFit: "趣味美食创意；可轻叠 fmcg，勿喧宾夺主。",
    topicHooks: ["howto做出谐音梗｜把梗做成菜之前，先算一口糖账"],
    laneHints: ["fmcg", "default"],
    summary: "把美食谐音梗做成一道真的菜。",
    windowHint: "07-06至07-31",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-lei-sect-2026",
    platform: "xiaohongshu",
    name: "申请加入擂门",
    kind: "topic_challenge",
    category: "fmcg_goods",
    featured: false,
    personaFit: "快餐门派玩梗；可法医式翻标，慎商业硬广。",
    topicHooks: [],
    laneHints: ["fmcg"],
    summary: "发布擂门笔记赢流量和周边。",
    windowHint: "07-06至08-31",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-pickle-sect-2026",
    platform: "xiaohongshu",
    name: "腌渍门出天才了",
    kind: "topic_challenge",
    category: "food_local",
    featured: false,
    personaFit: "自制腌渍/发酵美食线。",
    topicHooks: [],
    laneHints: ["fmcg", "default"],
    summary: "美食门派·腌渍门。",
    windowHint: "07-06起",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-worldcup-chat-2026",
    platform: "xiaohongshu",
    name: "世界杯聊个球",
    kind: "topic_challenge",
    category: "summer_lifestyle",
    featured: false,
    personaFit: "热点流量池；人设弱相关时可作辅话题（看球下酒菜叠 fmcg）。",
    topicHooks: ["搞定看球下酒菜｜糖盐账比比分更扎心"],
    laneHints: ["fmcg", "default"],
    summary: "来小红书看世界杯（05-29至07-31）。",
    windowHint: "05-29至07-31",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-ball-snacks-2026",
    platform: "xiaohongshu",
    name: "搞定看球下酒菜",
    kind: "topic_challenge",
    category: "fmcg_goods",
    featured: true,
    personaFit: "零食/下酒菜畅销品痛点槽点。",
    topicHooks: ["搞定看球下酒菜｜今晚霸屏配什么才不把糖账打穿"],
    laneHints: ["fmcg", "forensic"],
    summary: "看球配菜种草活动。",
    windowHint: "06-16至07-31",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-digital-support-2026",
    platform: "xiaohongshu",
    name: "小红书数码内容扶持活动",
    kind: "traffic_support",
    category: "tech_digital",
    featured: false,
    personaFit: "数码线弱相关；非主赛道可不挂。",
    topicHooks: [],
    laneHints: ["default"],
    summary: "数码内容官方扶持。",
    windowHint: "06-18至07-30",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-video-author-support-2026",
    platform: "xiaohongshu",
    name: "全站视频作者扶持 / 好视频扶持计划",
    kind: "traffic_support",
    category: "creator_incentive",
    featured: true,
    personaFit: "1.5–2 分钟讲解短视频（≤2分半硬上限；m2）优先蹭此激励。",
    topicHooks: [],
    laneHints: ["default", "fmcg"],
    summary: "发视频瓜分奖金；全站视频作者扶持中。",
    windowHint: "07-03起",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-wild-scientist-2026",
    platform: "xiaohongshu",
    name: "呼叫野生科学家",
    kind: "topic_challenge",
    category: "culture_reading",
    featured: true,
    personaFit: "轻科普交叉：机制要生活化，禁论文墙。",
    topicHooks: ["呼叫野生科学家｜糖账这道题，用货架就能算"],
    laneHints: ["fmcg", "crossover"],
    summary: "科学向创作激励。",
    windowHint: "06-24至07-31",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-100-daydreams-2026",
    platform: "xiaohongshu",
    name: "100个白日梦计划",
    kind: "topic_challenge",
    category: "summer_lifestyle",
    featured: false,
    personaFit: "愿望清单向；可写一场展一个梦。",
    topicHooks: [],
    laneHints: ["default"],
    summary: "白日梦计划活动。",
    windowHint: "07-02至07-31",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-half-cooked-parents-2026",
    platform: "xiaohongshu",
    name: "我的半熟爸妈",
    kind: "topic_challenge",
    category: "family_life",
    featured: false,
    personaFit: "亲子关系故事；强监管表达。",
    topicHooks: [],
    laneHints: ["default"],
    summary: "分享和爸妈的故事赢流量周边。",
    windowHint: "07-02至08-31",
    status: "active",
    sourceNote: "ac.mp4 创作者中心活动列表",
    reviewedAt: "2026-07-13",
  },
  // 游戏/IP 激励：入库但不精选（避免冲淡主方向）
  {
    id: "xhs-arknights-2026",
    platform: "xiaohongshu",
    name: "明日方舟创作应援",
    kind: "topic_challenge",
    category: "gaming_ip",
    featured: false,
    personaFit: "游戏 IP；与康养主线弱相关。",
    topicHooks: [],
    laneHints: ["default"],
    summary: "投稿互动可赢创作奖励。",
    windowHint: "07-10至07-31",
    status: "active",
    sourceNote: "ac.mp4",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-love-deepspace-2026",
    platform: "xiaohongshu",
    name: "恋与深空有奖征集",
    kind: "topic_challenge",
    category: "gaming_ip",
    featured: false,
    personaFit: "游戏征集；非主赛道。",
    topicHooks: [],
    laneHints: ["default"],
    summary: "恋与深空多重好礼助创作。",
    windowHint: "07-09至07-26",
    status: "active",
    sourceNote: "ac.mp4",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-sky-7th-2026",
    platform: "xiaohongshu",
    name: "光遇七周年创作征集",
    kind: "topic_challenge",
    category: "gaming_ip",
    featured: false,
    personaFit: "游戏周年征集。",
    topicHooks: [],
    laneHints: ["default"],
    summary: "光遇七周年创作激励。",
    windowHint: "06-29至08-18",
    status: "active",
    sourceNote: "ac.mp4",
    reviewedAt: "2026-07-13",
  },
  // 既有扶持（继续）
  {
    id: "xhs-red-newgen-2026",
    platform: "xiaohongshu",
    name: "RED 新生代创作大赛 / 创作基金",
    kind: "traffic_support",
    category: "creator_incentive",
    featured: true,
    personaFit: "人格化原创冷启动；可与图文合集同发。",
    topicHooks: [],
    laneHints: ["default"],
    summary: "综合创作大赛：赛事流量+创作基金。",
    status: "active",
    sourceNote: "既有扶持注册表·web 复核",
    reviewedAt: "2026-07-13",
  },
  {
    id: "xhs-midlong-video-2026",
    platform: "xiaohongshu",
    name: "小红书中长视频激励 / 视频激励计划",
    kind: "traffic_support",
    category: "creator_incentive",
    featured: true,
    personaFit: "1.5–2 分钟讲解短视频优先（≤2分半）。",
    topicHooks: [],
    laneHints: ["default", "fmcg"],
    summary: "中长视频流量券/创作基金。",
    status: "active",
    sourceNote: "既有扶持注册表·web 复核",
    reviewedAt: "2026-07-13",
  },
];

export const OTHER_PLATFORM_CAMPAIGN_SEEDS: OfficialCampaignSeed[] = [
  {
    id: "dy-ai-contest-2026",
    platform: "douyin",
    name: "抖音 AI 创作大赛 / AI 创作浪潮计划",
    kind: "traffic_support",
    category: "creator_incentive",
    featured: true,
    personaFit: "工具向叙事可借；康养主线仍用人设改写。",
    topicHooks: [],
    laneHints: ["default"],
    summary: "AI 创作官方征稿：现金+流量。",
    status: "active",
    sourceNote: "既有扶持注册表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "dy-knowledge-2026",
    platform: "douyin",
    name: "抖音知识节 / 知识区流量扶持",
    kind: "traffic_support",
    category: "creator_incentive",
    featured: true,
    personaFit: "口播 1.5–2 分钟知识讲解（≤2分半）；勿读论文。",
    topicHooks: [],
    laneHints: ["fmcg", "default"],
    summary: "知识向征稿/加权。",
    status: "active",
    sourceNote: "既有扶持注册表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "bili-task-center-2026",
    platform: "bilibili",
    name: "B站任务中心征稿（当月）",
    kind: "topic_challenge",
    category: "creator_incentive",
    featured: true,
    personaFit: "系列复盘/展评可投当月任务。",
    topicHooks: [],
    laneHints: ["default", "crossover"],
    summary: "月更征稿主题。",
    status: "active",
    sourceNote: "既有扶持注册表",
    reviewedAt: "2026-07-13",
  },
  {
    id: "ks-photosyn-2026",
    platform: "kuaishou",
    name: "快手光合计划与创作者成长扶持",
    kind: "traffic_support",
    category: "creator_incentive",
    featured: true,
    personaFit: "真实口播、强场景。",
    topicHooks: [],
    laneHints: ["default"],
    summary: "光合流量包。",
    status: "active",
    sourceNote: "既有扶持注册表",
    reviewedAt: "2026-07-13",
  },
];

export const ALL_OFFICIAL_CAMPAIGN_SEEDS: OfficialCampaignSeed[] = [
  ...XHS_OFFICIAL_CAMPAIGN_SEEDS,
  ...OTHER_PLATFORM_CAMPAIGN_SEEDS,
];

export function featuredOfficialCampaigns(platform?: string): OfficialCampaignSeed[] {
  return ALL_OFFICIAL_CAMPAIGN_SEEDS.filter(
    (c) => c.status === "active" && c.featured && (!platform || c.platform === platform),
  );
}

export function formatCampaignForReport(c: OfficialCampaignSeed): string {
  const win = c.windowHint ? `｜档期 ${c.windowHint}` : "";
  return `${c.name}：${c.summary}${win}（结合方向：${c.personaFit}）`;
}

export function formatCampaignTopicExamples(limit = 8): Array<{
  campaign: string;
  title: string;
  lane: OfficialCampaignLaneHint;
  category: OfficialCampaignCategory;
}> {
  const out: Array<{
    campaign: string;
    title: string;
    lane: OfficialCampaignLaneHint;
    category: OfficialCampaignCategory;
  }> = [];
  for (const c of featuredOfficialCampaigns("xiaohongshu")) {
    for (const hook of c.topicHooks) {
      out.push({
        campaign: c.name,
        title: hook,
        lane: c.laneHints[0] || "default",
        category: c.category,
      });
      if (out.length >= limit) return out;
    }
  }
  return out;
}
