/**
 * Qwen-Audio-3.0-TTS 基础音色目录（用户 2026-08-12 提供的官方两表，flash/plus 同一套
 * 音色后缀、仅模型前缀不同；共 597 条，年龄 6–72，含中英文）。
 *
 * voice 字段直接填 `qwen-audio-3.0-tts-{flash|plus}-{suffix}`（buildQwenTtsVoiceId 拼）。
 * 注意：qwenDialogueTts.ts 的两个短 id 系统音色（longanlingxin/longanlufeng）是另一命名系，
 * 目录 id 能否过 OpenRouter 待试听探测确认后再切默认。
 */

export type QwenTtsVoiceModel = "flash" | "plus";

export type QwenTtsVoiceEntry = {
  /** 音色后缀（两模型通用） */
  suffix: string;
  nameZh: string;
  gender: "男" | "女" | "中性";
  /** 音色标称年龄；个别行缺失为 null */
  age: number | null;
  traitZh: string;
  sceneZh: string;
  lang: string;
};

export function buildQwenTtsVoiceId(model: QwenTtsVoiceModel, suffix: string): string {
  return `qwen-audio-3.0-tts-${model}-${suffix}`;
}

export type QwenTtsCatalogVoiceCandidate = {
  voiceId: string;
  suffix: string;
  nameZh: string;
  availability: "candidate_unprobed";
};

/** 目录音色尚未经过 OpenRouter 试听探针；只能生成候选，不能冒充已可用。 */
export function qwenTtsCatalogVoiceCandidate(
  suffix: string,
  model: QwenTtsVoiceModel = "plus",
): QwenTtsCatalogVoiceCandidate | null {
  const entry = QWEN_TTS_VOICE_CATALOG.find((item) => item.suffix === suffix);
  return entry ? {
    voiceId: buildQwenTtsVoiceId(model, entry.suffix),
    suffix: entry.suffix,
    nameZh: entry.nameZh,
    availability: "candidate_unprobed",
  } : null;
}

/**
 * 按性别/年龄段/特质关键词挑音色（确定性取第一条，便于复现）。
 * 老人/小孩直接用 minAge/maxAge 圈（如老人 55+、小孩 ≤12），不再依赖克隆音色。
 */
export function pickQwenTtsVoice(opts: {
  gender?: "男" | "女" | "中性";
  minAge?: number;
  maxAge?: number;
  traitLike?: string;
  lang?: string;
}): QwenTtsVoiceEntry | null {
  for (const v of QWEN_TTS_VOICE_CATALOG) {
    if (opts.gender && v.gender !== opts.gender) continue;
    if (opts.lang && v.lang !== opts.lang) continue;
    if (opts.minAge != null && (v.age == null || v.age < opts.minAge)) continue;
    if (opts.maxAge != null && (v.age == null || v.age > opts.maxAge)) continue;
    if (opts.traitLike && !v.traitZh.includes(opts.traitLike) && !v.sceneZh.includes(opts.traitLike)) continue;
    return v;
  }
  return null;
}

export const QWEN_TTS_VOICE_CATALOG: QwenTtsVoiceEntry[] = [
  { suffix: "longcanzhuyue", nameZh: "龙璨竹月", gender: "女", age: 26, traitZh: "平实质朴音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longrongzhihe", nameZh: "龙蓉芷荷", gender: "女", age: 24, traitZh: "电台质感音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlanghongmo", nameZh: "龙朗虹沫", gender: "女", age: 25, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longfengyueyao", nameZh: "龙风月瑶", gender: "女", age: 28, traitZh: "直爽利落音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxiaoyuyue", nameZh: "龙潇煜月", gender: "女", age: 25, traitZh: "惊奇讶异音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longtongxuxian", nameZh: "龙彤旭弦", gender: "女", age: 24, traitZh: "活泼灵动音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longzhiqingxi", nameZh: "龙芷晴曦", gender: "女", age: 25, traitZh: "紧张不安音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlanbaixian", nameZh: "龙嵐柏弦", gender: "女", age: 17, traitZh: "惊悚恐怖音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyingsongliu", nameZh: "龙莹松柳", gender: "男", age: 32, traitZh: "爽朗利落音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longzhengyaohe", nameZh: "龙筝瑶鹤", gender: "男", age: 38, traitZh: "亢奋激昂音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlanyufu", nameZh: "龙岚煜芙", gender: "男", age: 22, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longnixiulian", nameZh: "龙霓岫涟", gender: "男", age: 25, traitZh: "内敛含蓄音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxilingxuan", nameZh: "龙溪凌璇", gender: "男", age: 28, traitZh: "不满犀利音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longchengtaohui", nameZh: "龙澄桃晦", gender: "男", age: 23, traitZh: "不满犀利音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxinruixuan", nameZh: "龙昕蕊璇", gender: "男", age: 24, traitZh: "自然亲和音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longqinheying", nameZh: "龙琴鹤莹", gender: "男", age: 24, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longxianshuohui", nameZh: "龙弦朔晖", gender: "男", age: 68, traitZh: "激昂朗诵音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longliannirong", nameZh: "龙涟霓蓉", gender: "男", age: 42, traitZh: "平稳陈述音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longheweican", nameZh: "龙鹤薇璨", gender: "男", age: 42, traitZh: "平稳陈述音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longzhishuoke", nameZh: "龙芷朔珂", gender: "男", age: 45, traitZh: "平稳陈述音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longruifengyu", nameZh: "龙蕊风瑜", gender: "男", age: 42, traitZh: "平稳陈述音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longluliuche", nameZh: "龙露柳澈", gender: "男", age: 34, traitZh: "标准播音音", sceneZh: "新闻播报", lang: "中文" },
  { suffix: "longliuxulan", nameZh: "龙柳旭澜", gender: "女", age: 25, traitZh: "标准播音音", sceneZh: "新闻播报", lang: "中文" },
  { suffix: "longjufuhe", nameZh: "龙菊芙荷", gender: "女", age: 7, traitZh: "呆萌软糯音", sceneZh: "动漫配音", lang: "中文" },
  { suffix: "longxiamuyan", nameZh: "龙霞暮燕", gender: "男", age: 26, traitZh: "专业解说音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyuzhihe", nameZh: "龙羽芷荷", gender: "男", age: 42, traitZh: "客观冷静音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyaolanshuang", nameZh: "龙瑶岚霜", gender: "男", age: 27, traitZh: "鼓舞激励音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longsongyibai", nameZh: "龙松熠柏", gender: "男", age: 27, traitZh: "鼓舞激励音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyanhuilu", nameZh: "龙燕辉露", gender: "男", age: 27, traitZh: "客观冷静音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longhuifengyi", nameZh: "龙辉峰漪", gender: "男", age: 26, traitZh: "客观冷静音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longshuojizhu", nameZh: "龙朔霁竹", gender: "男", age: 26, traitZh: "标准播音音", sceneZh: "新闻播报", lang: "中文" },
  { suffix: "longhuiyanzhu", nameZh: "龙晖妍竹", gender: "男", age: 26, traitZh: "标准播音音", sceneZh: "新闻播报", lang: "中文" },
  { suffix: "longbaixiuyun", nameZh: "龙柏岫云", gender: "男", age: 25, traitZh: "标准播音音", sceneZh: "新闻播报", lang: "中文" },
  { suffix: "longxiaolanshan", nameZh: "龙潇嵐杉", gender: "男", age: 28, traitZh: "标准播音音", sceneZh: "新闻播报", lang: "中文" },
  { suffix: "longyilincan", nameZh: "龙熠琳璨", gender: "男", age: 24, traitZh: "标准播音音", sceneZh: "新闻播报", lang: "中文" },
  { suffix: "longsongyilan", nameZh: "龙松翼嵐", gender: "男", age: 26, traitZh: "激动振奋音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longhuikeyuan", nameZh: "龙辉珂渊", gender: "女", age: 28, traitZh: "标准播音音", sceneZh: "新闻播报", lang: "中文" },
  { suffix: "longyujunxuan", nameZh: "龙羽珺萱", gender: "女", age: 25, traitZh: "温柔坚韧音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longchexini", nameZh: "龙澈溪霓", gender: "女", age: 23, traitZh: "科普讲解音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlanlianlan", nameZh: "龙嵐涟兰", gender: "女", age: 23, traitZh: "直播带货音", sceneZh: "电商直播", lang: "中文" },
  { suffix: "longlingtongfu", nameZh: "龙凌桐芙", gender: "女", age: 28, traitZh: "直播带货音", sceneZh: "电商直播", lang: "中文" },
  { suffix: "longliumolan", nameZh: "龙柳沫岚", gender: "女", age: 24, traitZh: "直播带货音", sceneZh: "电商直播", lang: "中文" },
  { suffix: "longtongjunfeng", nameZh: "龙彤珺凤", gender: "女", age: 25, traitZh: "轻松闲聊音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longquetingqing", nameZh: "龙鹊汀晴", gender: "女", age: 24, traitZh: "直播带货音", sceneZh: "电商直播", lang: "中文" },
  { suffix: "longzhiluyan", nameZh: "龙芷露妍", gender: "女", age: 7, traitZh: "直播带货音", sceneZh: "电商直播", lang: "中文" },
  { suffix: "longxizhiyun", nameZh: "龙曦芷云", gender: "女", age: 25, traitZh: "直播带货音", sceneZh: "电商直播", lang: "中文" },
  { suffix: "longruiloufeng", nameZh: "龙蕊露风", gender: "女", age: 23, traitZh: "轻松闲聊音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longquanxiangxuan", nameZh: "龙泉湘萱", gender: "女", age: 25, traitZh: "直播带货音", sceneZh: "电商直播", lang: "中文" },
  { suffix: "longronglinglin", nameZh: "龙蓉岭麟", gender: "男", age: 24, traitZh: "活泼灵动音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longqinxinque", nameZh: "龙琴昕雀", gender: "男", age: 26, traitZh: "客观冷静音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlinfengni", nameZh: "龙麟峰霓", gender: "男", age: 38, traitZh: "客观冷静音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyufengni", nameZh: "龙雨凤霓", gender: "男", age: 25, traitZh: "愤懑不平音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longrongtaolian", nameZh: "龙蓉桃涟", gender: "男", age: 34, traitZh: "冷静沉稳音", sceneZh: "有声阅读", lang: "中文" },
  { suffix: "longyanfengying", nameZh: "龙燕枫莹", gender: "男", age: 24, traitZh: "冷静沉稳音", sceneZh: "有声阅读", lang: "中文" },
  { suffix: "longquanqueling", nameZh: "龙泉鹊凌", gender: "女", age: 23, traitZh: "娇嗲甜腻音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxumoxiao", nameZh: "龙旭沫晓", gender: "女", age: 26, traitZh: "温柔细腻音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longtonglinyuan", nameZh: "龙桐麟渊", gender: "女", age: 26, traitZh: "温柔细腻音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longfengyutong", nameZh: "龙凤雨桐", gender: "女", age: 27, traitZh: "标准播音音", sceneZh: "新闻播报", lang: "中文" },
  { suffix: "longhongfuxiu", nameZh: "龙鸿芙岫", gender: "女", age: 42, traitZh: "标准播音音", sceneZh: "新闻播报", lang: "中文" },
  { suffix: "longxiannixiao", nameZh: "龙弦霓霄", gender: "女", age: 26, traitZh: "温柔细腻音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longsongtaoxuan", nameZh: "龙松桃璇", gender: "女", age: 25, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longmuhongmo", nameZh: "龙暮虹沫", gender: "女", age: 24, traitZh: "温柔细腻音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyushuangmu", nameZh: "龙雨霜暮", gender: "女", age: 28, traitZh: "直播讲解音", sceneZh: "电商直播", lang: "中文" },
  { suffix: "longyuxiangxi", nameZh: "龙雨湘溪", gender: "女", age: 28, traitZh: "直播讲解音", sceneZh: "电商直播", lang: "中文" },
  { suffix: "longluhuilang", nameZh: "龙露辉朗", gender: "女", age: 25, traitZh: "直播讲解音", sceneZh: "电商直播", lang: "中文" },
  { suffix: "longfengmeiche", nameZh: "龙凤梅澈", gender: "女", age: 25, traitZh: "直播讲解音", sceneZh: "电商直播", lang: "中文" },
  { suffix: "longshuoxidie", nameZh: "龙烁溪蝶", gender: "女", age: 26, traitZh: "直播讲解音", sceneZh: "电商直播", lang: "中文" },
  { suffix: "longfuyingxuan", nameZh: "龙芙樱暄", gender: "女", age: 26, traitZh: "温柔细腻音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longxuanfuluan", nameZh: "龙萱芙鸾", gender: "男", age: 28, traitZh: "温柔细腻音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longxiuyulan", nameZh: "龙岫瑜岚", gender: "男", age: 26, traitZh: "温婉成熟音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longxiushuoche", nameZh: "龙岫烁澈", gender: "女", age: 26, traitZh: "温柔坚韧音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longlianliuxiao", nameZh: "龙涟柳潇", gender: "女", age: 24, traitZh: "温柔坚韧音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longlanlurong", nameZh: "龙岚露蓉", gender: "女", age: 25, traitZh: "客观冷静音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longbaiquemo", nameZh: "龙柏鹊沫", gender: "女", age: 23, traitZh: "委屈哀怨音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyanxuyi", nameZh: "龙焱旭漪", gender: "女", age: 24, traitZh: "急躁焦灼音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxinzhenghe", nameZh: "龙昕筝荷", gender: "女", age: 42, traitZh: "温柔坚韧音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longzhengxialing", nameZh: "龙筝霞凌", gender: "女", age: 25, traitZh: "客观冷静音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyingshuocan", nameZh: "龙樱朔璨", gender: "男", age: 25, traitZh: "温稳沉着音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longlinghuiyan", nameZh: "龙凌晦燕", gender: "男", age: 36, traitZh: "客观冷静音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longzhuquanwang", nameZh: "龙竹泉望", gender: "女", age: 14, traitZh: "撒娇甜蜜音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyimuling", nameZh: "龙翼暮凌", gender: "男", age: 38, traitZh: "沉稳有力音", sceneZh: "有声阅读", lang: "中文" },
  { suffix: "longlanxuejun", nameZh: "龙兰雪珺", gender: "女", age: 10, traitZh: "温柔活泼音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longlingyingshuo", nameZh: "龙翎樱朔", gender: "女", age: 24, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longlingxiaolin", nameZh: "龙翎霄麟", gender: "女", age: 24, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longshanhongyue", nameZh: "龙杉虹玥", gender: "女", age: 28, traitZh: "惊奇讶异音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxianzhenghe", nameZh: "龙弦筝鹤", gender: "女", age: 25, traitZh: "激情澎湃音", sceneZh: "体育解说", lang: "中文" },
  { suffix: "longlingzhixing", nameZh: "龙岭芷杏", gender: "男", age: 68, traitZh: "浑厚沉稳音", sceneZh: "有声阅读", lang: "中文" },
  { suffix: "longlanjunrui", nameZh: "龙岚珺蕊", gender: "男", age: 43, traitZh: "浑厚沉稳音", sceneZh: "有声阅读", lang: "中文" },
  { suffix: "longxintaofeng", nameZh: "龙昕桃凤", gender: "男", age: 58, traitZh: "浑厚沉稳音", sceneZh: "有声阅读", lang: "中文" },
  { suffix: "longluyinglan", nameZh: "龙露莹岚", gender: "男", age: 45, traitZh: "惊恐不安音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlanglianyue", nameZh: "龙朗涟玥", gender: "男", age: 55, traitZh: "浑厚沉稳音", sceneZh: "有声阅读", lang: "中文" },
  { suffix: "longfushanmu", nameZh: "龙芙杉暮", gender: "男", age: 56, traitZh: "浑厚沉稳音", sceneZh: "有声阅读", lang: "中文" },
  { suffix: "longqueyuxiang", nameZh: "龙雀煜湘", gender: "男", age: 24, traitZh: "撒娇甜蜜音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longchengtaolian", nameZh: "龙澄桃莲", gender: "男", age: 70, traitZh: "灵动戏腔音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyuntinglian", nameZh: "龙云汀涟", gender: "女", age: 24, traitZh: "撒娇甜蜜音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyuquelu", nameZh: "龙羽雀露", gender: "女", age: 25, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longjilinxiao", nameZh: "龙霁琳潇", gender: "女", age: 23, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyanchelin", nameZh: "龙焱澈琳", gender: "男", age: 7, traitZh: "激动振奋音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlinjinying", nameZh: "龙琳瑾樱", gender: "女", age: 38, traitZh: "耐心温和音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyaolanxuan", nameZh: "龙瑶岚萱", gender: "男", age: 25, traitZh: "傲娇俏皮音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longzhixingju", nameZh: "龙芷杏菊", gender: "女", age: 27, traitZh: "智能助手音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longronglingyan", nameZh: "龙蓉岭焱", gender: "女", age: 26, traitZh: "智能助手音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxiudieyi", nameZh: "龙岫蝶熠", gender: "女", age: 25, traitZh: "智能助手音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longtongxianhong", nameZh: "龙彤弦鸿", gender: "男", age: 26, traitZh: "二次元活力音", sceneZh: "动漫配音", lang: "中文" },
  { suffix: "longrongjuxu", nameZh: "龙蓉菊旭", gender: "男", age: 25, traitZh: "二次元活力音", sceneZh: "动漫配音", lang: "中文" },
  { suffix: "longlanzhengyan", nameZh: "龙岚筝燕", gender: "男", age: 24, traitZh: "二次元活力音", sceneZh: "动漫配音", lang: "中文" },
  { suffix: "longxiantingfeng", nameZh: "龙弦汀峰", gender: "男", age: 25, traitZh: "激动振奋音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longmeixiuhe", nameZh: "龙梅岫荷", gender: "男", age: 21, traitZh: "二次元活力音", sceneZh: "动漫配音", lang: "中文" },
  { suffix: "longxuanyixiao", nameZh: "龙暄漪霄", gender: "男", age: 7, traitZh: "二次元活力音", sceneZh: "动漫配音", lang: "中文" },
  { suffix: "longlanqueyan", nameZh: "龙岚鹊焱", gender: "女", age: 15, traitZh: "动漫风格音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longtingyuanyi", nameZh: "龙汀渊熠", gender: "女", age: 23, traitZh: "委屈哀怨音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longhesongrui", nameZh: "龙荷松蕊", gender: "男", age: 44, traitZh: "叙事沉浸音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longsonghuiliu", nameZh: "龙松晦柳", gender: "男", age: 25, traitZh: "不满犀利音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlinyuemo", nameZh: "龙麟玥沫", gender: "男", age: 28, traitZh: "客观冷静音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyuyingdie", nameZh: "龙雨樱蝶", gender: "男", age: 28, traitZh: "智能助手音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxianxinglan", nameZh: "龙弦星嵐", gender: "女", age: 28, traitZh: "自然聊天音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longchuanyunling", nameZh: "龙川云翎", gender: "女", age: 8, traitZh: "搞怪逗趣音", sceneZh: "娱乐搞笑", lang: "中文" },
  { suffix: "longdielianxia", nameZh: "龙蝶涟霞", gender: "女", age: 26, traitZh: "智能助手音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyuanzhiwei", nameZh: "龙渊芷薇", gender: "男", age: 22, traitZh: "智能助手音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyuehongyan", nameZh: "龙月鸿妍", gender: "男", age: 7, traitZh: "客观冷静音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longjitongfeng", nameZh: "龙霁桐峰", gender: "男", age: 10, traitZh: "惊恐不安音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longluanxiche", nameZh: "龙鸾曦澈", gender: "男", age: 8, traitZh: "不屑倨傲音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxihuiyan", nameZh: "龙溪晖燕", gender: "男", age: 10, traitZh: "自信笃定音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longfengshuangfu", nameZh: "龙枫霜芙", gender: "男", age: 27, traitZh: "客观冷静音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longliuxiuke", nameZh: "龙柳岫珂", gender: "男", age: 8, traitZh: "客观冷静音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyinglandie", nameZh: "龙莹岚蝶", gender: "男", age: 7, traitZh: "撒娇甜蜜音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlingxingxia", nameZh: "龙岭星霞", gender: "女", age: 23, traitZh: "客观冷静音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlanzhixu", nameZh: "龙岚芷旭", gender: "女", age: 8, traitZh: "自然亲和音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlanyuerong", nameZh: "龙岚月蓉", gender: "女", age: 9, traitZh: "客观冷静音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longshuosongxuan", nameZh: "龙烁松萱", gender: "女", age: 7, traitZh: "欢乐明朗音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxuanzhuche", nameZh: "龙暄竹澈", gender: "女", age: 7, traitZh: "欢乐明朗音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxianlianyi", nameZh: "龙弦莲翼", gender: "女", age: 7, traitZh: "惊恐不安音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longbaijunzheng", nameZh: "龙柏珺筝", gender: "女", age: 7, traitZh: "伤感低回音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longtongxingquan", nameZh: "龙彤杏泉", gender: "男", age: 42, traitZh: "叙事沉浸音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyirongzheng", nameZh: "龙熠蓉筝", gender: "男", age: 8, traitZh: "动漫风格音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longshuohuimei", nameZh: "龙朔辉梅", gender: "男", age: 70, traitZh: "轻松闲聊音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longluxiaohui", nameZh: "龙露潇晖", gender: "男", age: 35, traitZh: "亲切客服音", sceneZh: "智能客服", lang: "中文" },
  { suffix: "longshanniting", nameZh: "龙杉霓汀", gender: "男", age: 28, traitZh: "亲切客服音", sceneZh: "智能客服", lang: "中文" },
  { suffix: "longnixiwei", nameZh: "龙霓曦薇", gender: "男", age: 38, traitZh: "新闻联播音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longcheyanxuan", nameZh: "龙澈焱暄", gender: "女", age: 25, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyuelanke", nameZh: "龙月澜珂", gender: "女", age: 24, traitZh: "期待向往音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longliulingfu", nameZh: "龙柳翎芙", gender: "女", age: 27, traitZh: "忧郁低回音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longhuitongyuan", nameZh: "龙晖彤渊", gender: "女", age: 8, traitZh: "娇嗲甜腻音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyaoxuanzhi", nameZh: "龙瑶璇芷", gender: "女", age: 24, traitZh: "客观冷静音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longjunxinmu", nameZh: "龙珺昕暮", gender: "女", age: 25, traitZh: "灵动好奇音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlingyilan", nameZh: "龙凌漪岚", gender: "女", age: 25, traitZh: "温柔坚韧音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longlingxianxiu", nameZh: "龙翎弦岫", gender: "女", age: 24, traitZh: "灵动好奇音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlianruimei", nameZh: "龙莲蕊梅", gender: "女", age: 24, traitZh: "循循善诱音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyumeixia", nameZh: "龙瑜梅霞", gender: "女", age: 24, traitZh: "叙事沉浸音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longtaoliuhong", nameZh: "龙桃柳虹", gender: "女", age: 24, traitZh: "活泼灵动音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longjixilan", nameZh: "龙霁曦嵐", gender: "女", age: 25, traitZh: "铿锵有力音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longqintaoxuan", nameZh: "龙琴桃璇", gender: "女", age: 26, traitZh: "激动振奋音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longzhengxiaocheng", nameZh: "龙筝晓澄", gender: "女", age: 27, traitZh: "铿锵有力音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longchuanqueyan", nameZh: "龙川鹊妍", gender: "女", age: 27, traitZh: "铿锵有力音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlianchuanzhu", nameZh: "龙莲川竹", gender: "男", age: 42, traitZh: "忧郁深沉音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longfengyuanquan", nameZh: "龙凤渊泉", gender: "女", age: 24, traitZh: "甜萌可爱音", sceneZh: "动漫配音", lang: "中文" },
  { suffix: "longsongchelin", nameZh: "龙松澈琳", gender: "男", age: 40, traitZh: "客观冷静音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longmeixiaolan", nameZh: "龙梅霄嵐", gender: "男", age: 38, traitZh: "爽朗利落音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longtingheqing", nameZh: "龙汀鹤晴", gender: "男", age: 25, traitZh: "不屑倨傲音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxiyanjun", nameZh: "龙曦燕珺", gender: "男", age: 27, traitZh: "客观冷静音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyanhongqin", nameZh: "龙焱虹琴", gender: "男", age: 28, traitZh: "犀利刻薄音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyiliufu", nameZh: "龙熠柳芙", gender: "男", age: 28, traitZh: "客观冷静音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longbaixuanshan", nameZh: "龙柏萱杉", gender: "男", age: 32, traitZh: "鼓励认可音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longbaiyunlin", nameZh: "龙柏云麟", gender: "女", age: 23, traitZh: "不满犀利音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxuanfengrui", nameZh: "龙璇风蕊", gender: "女", age: 15, traitZh: "惊恐不安音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longweijuquan", nameZh: "龙薇菊泉", gender: "男", age: 40, traitZh: "叙事沉浸音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longjunhuixia", nameZh: "龙珺辉霞", gender: "女", age: 24, traitZh: "自然亲和音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longquemeifeng", nameZh: "龙鹊梅峰", gender: "男", age: 38, traitZh: "谆谆劝导音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxianfengwei", nameZh: "龙弦凤薇", gender: "女", age: 26, traitZh: "亲切客服音", sceneZh: "智能客服", lang: "中文" },
  { suffix: "longquexihui", nameZh: "龙鹊溪辉", gender: "女", age: 28, traitZh: "智能助手音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyaoruilang", nameZh: "龙瑶蕊朗", gender: "女", age: 25, traitZh: "惋惜叹惋音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlanlangwei", nameZh: "龙嵐朗薇", gender: "女", age: 24, traitZh: "轻松愉悦音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyingfengmu", nameZh: "龙莹枫暮", gender: "女", age: 28, traitZh: "客观冷静音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyaolinglan", nameZh: "龙瑶岭岚", gender: "女", age: 25, traitZh: "耐心温和音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longkexuanzheng", nameZh: "龙珂暄筝", gender: "女", age: 24, traitZh: "激动振奋音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyuelinwang", nameZh: "龙玥麟望", gender: "女", age: 25, traitZh: "亲切客服音", sceneZh: "智能客服", lang: "中文" },
  { suffix: "longtaotingyu", nameZh: "龙桃汀羽", gender: "女", age: 27, traitZh: "亲切客服音", sceneZh: "智能客服", lang: "中文" },
  { suffix: "longxianyuanmei", nameZh: "龙弦渊梅", gender: "女", age: 34, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longhuibaijun", nameZh: "龙晦柏珺", gender: "女", age: 26, traitZh: "温柔细腻音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longlinglinyao", nameZh: "龙凌麟瑶", gender: "男", age: 27, traitZh: "温柔细腻音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longfengmeihui", nameZh: "龙峰梅晖", gender: "女", age: 26, traitZh: "利落麻利音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlantongxuan", nameZh: "龙澜彤璇", gender: "女", age: 24, traitZh: "电台质感音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longdiechuanling", nameZh: "龙蝶川岭", gender: "女", age: 25, traitZh: "叙事沉浸音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlingjuhong", nameZh: "龙凌菊鸿", gender: "女", age: 9, traitZh: "温柔坚韧音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyunjinji", nameZh: "龙云瑾霁", gender: "男", age: 24, traitZh: "撒娇甜蜜音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longsongqinglian", nameZh: "龙松晴涟", gender: "男", age: 24, traitZh: "忧伤低回音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyuelinglan", nameZh: "龙玥凌嵐", gender: "男", age: 19, traitZh: "激动振奋音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxiuketao", nameZh: "龙岫珂桃", gender: "男", age: 24, traitZh: "傲娇俏皮音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longchenghongrui", nameZh: "龙澄鸿蕊", gender: "男", age: 28, traitZh: "沮丧低落音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxueyuxia", nameZh: "龙雪瑜霞", gender: "女", age: 24, traitZh: "温雅端庄音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longhongxinxu", nameZh: "龙鸿昕旭", gender: "男", age: 15, traitZh: "自然亲和音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longfenglanxiao", nameZh: "龙风兰潇", gender: "男", age: 8, traitZh: "元气活力音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longqinqueyi", nameZh: "龙琴鹊漪", gender: "男", age: 16, traitZh: "自然亲和音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longquanlingfu", nameZh: "龙泉岭芙", gender: "男", age: 7, traitZh: "惊恐不安音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxuxiyue", nameZh: "龙旭溪玥", gender: "男", age: 14, traitZh: "惊恐不安音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longmofengshuo", nameZh: "龙沫风烁", gender: "男", age: 13, traitZh: "自信从容音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyishuojin", nameZh: "龙熠朔瑾", gender: "男", age: 9, traitZh: "不满犀利音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longqueqinlan", nameZh: "龙雀琴嵐", gender: "女", age: 22, traitZh: "呆萌软糯音", sceneZh: "动漫配音", lang: "中文" },
  { suffix: "longquetongwang", nameZh: "龙鹊桐望", gender: "女", age: 8, traitZh: "甜萌可爱音", sceneZh: "动漫配音", lang: "中文" },
  { suffix: "longxuekeyu", nameZh: "龙雪珂雨", gender: "女", age: 8, traitZh: "智能助手音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyiqueju", nameZh: "龙翼雀菊", gender: "女", age: 7, traitZh: "搞怪逗趣音", sceneZh: "娱乐搞笑", lang: "中文" },
  { suffix: "longcheshuofeng", nameZh: "龙澈朔枫", gender: "女", age: 9, traitZh: "惊恐不安音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlanmuju", nameZh: "龙澜暮菊", gender: "女", age: 6, traitZh: "伤感低回音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longcanlianxiu", nameZh: "龙璨莲岫", gender: "女", age: 8, traitZh: "不耐烦躁音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longcanyanwang", nameZh: "龙璨燕望", gender: "男", age: 42, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlinxinghong", nameZh: "龙琳杏鸿", gender: "女", age: 25, traitZh: "客观冷静音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longchengxuanxian", nameZh: "龙澄璇弦", gender: "女", age: 25, traitZh: "客观冷静音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyuxialan", nameZh: "龙煜霞澜", gender: "女", age: 24, traitZh: "惊喜意外音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longruiyuling", nameZh: "龙蕊煜翎", gender: "女", age: 24, traitZh: "客观冷静音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyiqinhui", nameZh: "龙熠琴晖", gender: "男", age: 26, traitZh: "憨萌逗趣音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longquefengmu", nameZh: "龙鹊风暮", gender: "男", age: 8, traitZh: "青春朝气音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyaoxuanke", nameZh: "龙瑶璇珂", gender: "女", age: 7, traitZh: "天真童趣音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longshanxinglan", nameZh: "龙杉杏兰", gender: "女", age: 8, traitZh: "天真童趣音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyixiaowei", nameZh: "龙漪潇薇", gender: "女", age: 24, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longlianchuanxuan", nameZh: "龙莲川璇", gender: "男", age: 29, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longzhufengquan", nameZh: "龙竹峰泉", gender: "女", age: 26, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longlangjiluan", nameZh: "龙朗霁鸾", gender: "男", age: 27, traitZh: "沉稳大气音", sceneZh: "有声阅读", lang: "中文" },
  { suffix: "longyuyaoluan", nameZh: "龙羽瑶鸾", gender: "女", age: 25, traitZh: "沉稳大气音", sceneZh: "有声阅读", lang: "中文" },
  { suffix: "longlianmeixiu", nameZh: "龙涟梅岫", gender: "女", age: 24, traitZh: "温稳沉着音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longmuhecan", nameZh: "龙暮鹤璨", gender: "女", age: 25, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longlangruiling", nameZh: "龙朗蕊岭", gender: "男", age: 26, traitZh: "青春朝气音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyanzhihui", nameZh: "龙焱芷晖", gender: "男", age: 25, traitZh: "温润磁性音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longxianlinxu", nameZh: "龙弦琳旭", gender: "女", age: 25, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longhexuefeng", nameZh: "龙荷雪风", gender: "女", age: 24, traitZh: "角色模仿音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longzhuqinxuan", nameZh: "龙竹琴萱", gender: "男", age: 43, traitZh: "角色模仿音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longhongxiuyi", nameZh: "龙鸿岫翼", gender: "女", age: 7, traitZh: "天真童趣音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxixiani", nameZh: "龙曦霞霓", gender: "女", age: 7, traitZh: "天真童趣音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxuqinyuan", nameZh: "龙旭琴渊", gender: "男", age: 26, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyingfengwang", nameZh: "龙莹风望", gender: "女", age: 26, traitZh: "温柔邻家音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longquexuanyu", nameZh: "龙鹊萱羽", gender: "男", age: 56, traitZh: "灵动戏腔音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longmohuiling", nameZh: "龙沫晖翎", gender: "女", age: 26, traitZh: "御姐成熟音", sceneZh: "有声书配音", lang: "中文" },
  { suffix: "longyingtaomei", nameZh: "龙莹桃梅", gender: "男", age: 28, traitZh: "温润磁性音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyaoxinliu", nameZh: "龙瑶昕柳", gender: "女", age: 25, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longshuangyuerong", nameZh: "龙霜玥蓉", gender: "男", age: 26, traitZh: "青春朝气音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlulanling", nameZh: "龙露嵐凌", gender: "男", age: 25, traitZh: "青春朝气音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longruiyueju", nameZh: "龙蕊玥菊", gender: "女", age: 25, traitZh: "温婉干练音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyingjulan", nameZh: "龙莹菊兰", gender: "女", age: 25, traitZh: "温稳沉着音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longshanzhuxin", nameZh: "龙杉竹昕", gender: "女", age: 25, traitZh: "温柔老练音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longlanxiaoling", nameZh: "龙兰晓翎", gender: "女", age: 25, traitZh: "邻家亲切音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxikexing", nameZh: "龙曦珂星", gender: "女", age: 7, traitZh: "慵懒童趣音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longshuanglanhong", nameZh: "龙霜兰虹", gender: "女", age: 9, traitZh: "慵懒童趣音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxialuling", nameZh: "龙霞露岭", gender: "女", age: 9, traitZh: "调皮少年音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxiangxizheng", nameZh: "龙湘曦筝", gender: "女", age: 22, traitZh: "温柔活泼音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyanxueni", nameZh: "龙焱雪霓", gender: "女", age: 8, traitZh: "慵懒童趣音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxiuhuiyue", nameZh: "龙岫晖月", gender: "女", age: 8, traitZh: "角色模仿音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longfengyanshuo", nameZh: "龙凤燕朔", gender: "女", age: 10, traitZh: "机灵少年音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longtongquequan", nameZh: "龙彤鹊泉", gender: "女", age: 10, traitZh: "活泼灵动音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyujulu", nameZh: "龙煜菊露", gender: "男", age: 24, traitZh: "青春朝气音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longshuocanmu", nameZh: "龙烁璨暮", gender: "女", age: 22, traitZh: "青春朝气音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longhehuiyi", nameZh: "龙鹤辉漪", gender: "女", age: 25, traitZh: "活泼灵动音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxiaoyuque", nameZh: "龙潇煜雀", gender: "女", age: 23, traitZh: "活泼灵动音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxulingji", nameZh: "龙旭凌霁", gender: "女", age: 24, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longqueqingrui", nameZh: "龙雀晴蕊", gender: "男", age: 25, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longxiufengdie", nameZh: "龙岫凤蝶", gender: "女", age: 24, traitZh: "温柔知性音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyuyanxuan", nameZh: "龙瑜燕暄", gender: "女", age: 24, traitZh: "温稳沉着音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longsongshuoling", nameZh: "龙松朔岭", gender: "女", age: 8, traitZh: "活泼灵动音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxiyaoque", nameZh: "龙溪瑶雀", gender: "男", age: 25, traitZh: "活泼灵动音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlanxiaoyu", nameZh: "龙兰霄雨", gender: "女", age: 21, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longxuanmeilin", nameZh: "龙暄梅麟", gender: "女", age: 26, traitZh: "温稳沉着音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longjishuangjin", nameZh: "龙霁霜瑾", gender: "女", age: 26, traitZh: "角色模仿音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlingzhengcheng", nameZh: "龙翎筝澄", gender: "女", age: 23, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longsongxinchuan", nameZh: "龙松昕川", gender: "女", age: 23, traitZh: "温柔邻家音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longlanxiaoyi", nameZh: "龙岚霄翼", gender: "女", age: 23, traitZh: "邻家亲切音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longchengzhiyan", nameZh: "龙澄芷燕", gender: "女", age: 25, traitZh: "沉稳大气音", sceneZh: "有声阅读", lang: "中文" },
  { suffix: "longyuxinwang", nameZh: "龙煜昕望", gender: "女", age: 8, traitZh: "角色模仿音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longfengweixian", nameZh: "龙枫薇弦", gender: "女", age: 24, traitZh: "温柔知性音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyanlanyun", nameZh: "龙妍岚云", gender: "女", age: 25, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longchexinfeng", nameZh: "龙澈昕凤", gender: "女", age: 26, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longhongcanyue", nameZh: "龙虹璨月", gender: "女", age: 25, traitZh: "活泼灵动音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longhediexiu", nameZh: "龙鹤蝶岫", gender: "女", age: 25, traitZh: "温柔坚韧音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyijunji", nameZh: "龙翼珺霁", gender: "女", age: 23, traitZh: "心机绿茶音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longshuangsongbai", nameZh: "龙霜松柏", gender: "女", age: 24, traitZh: "温柔俏皮音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longlangxiwei", nameZh: "龙朗溪薇", gender: "女", age: 25, traitZh: "温婉成熟音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyuanyuque", nameZh: "龙渊煜鹊", gender: "女", age: 24, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longliulanxiang", nameZh: "龙柳岚湘", gender: "女", age: 25, traitZh: "温柔青春音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longquezhujin", nameZh: "龙雀竹瑾", gender: "女", age: 16, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyixuanjun", nameZh: "龙漪暄珺", gender: "女", age: 36, traitZh: "成熟沉稳音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longluanhuiyu", nameZh: "龙鸾辉雨", gender: "女", age: 24, traitZh: "成熟沉稳音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlinliuhe", nameZh: "龙琳柳荷", gender: "女", age: 25, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxuankemei", nameZh: "龙璇珂梅", gender: "女", age: 24, traitZh: "温婉成熟音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longxiaqueshan", nameZh: "龙霞雀杉", gender: "男", age: 25, traitZh: "搞怪逗趣音", sceneZh: "娱乐搞笑", lang: "中文" },
  { suffix: "longlianhuirui", nameZh: "龙涟晦蕊", gender: "女", age: 26, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longquanluanhong", nameZh: "龙泉鸾虹", gender: "男", age: 24, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxingxiuquan", nameZh: "龙星岫泉", gender: "女", age: 24, traitZh: "温婉成熟音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longchengyanfeng", nameZh: "龙澄燕凤", gender: "女", age: 24, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxuanzhufeng", nameZh: "龙璇竹凤", gender: "女", age: 24, traitZh: "温婉成熟音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longtongshuoxiu", nameZh: "龙桐烁岫", gender: "女", age: 25, traitZh: "爽朗利落音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyaoquezheng", nameZh: "龙瑶雀筝", gender: "女", age: 25, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxifengyi", nameZh: "龙曦凤漪", gender: "女", age: 25, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longjunxiayan", nameZh: "龙珺霞妍", gender: "女", age: 8, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longtongquanxiang", nameZh: "龙桐泉湘", gender: "女", age: 25, traitZh: "温婉成熟音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyixiangtao", nameZh: "龙漪湘桃", gender: "女", age: 27, traitZh: "温婉成熟音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longlannihui", nameZh: "龙岚霓晖", gender: "女", age: 25, traitZh: "温柔青春音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longxuanzhengju", nameZh: "龙萱筝菊", gender: "女", age: 26, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longshanyusong", nameZh: "龙杉煜松", gender: "女", age: 25, traitZh: "平稳陈述音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longshanyilan", nameZh: "龙杉熠澜", gender: "女", age: 14, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longshuochehui", nameZh: "龙朔澈晖", gender: "女", age: 26, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyiyusong", nameZh: "龙熠瑜松", gender: "女", age: 24, traitZh: "活泼灵动音", sceneZh: "社交互动", lang: "中文" },
  { suffix: "longlingqueyi", nameZh: "龙岭鹊熠", gender: "女", age: 24, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxiyuling", nameZh: "龙曦雨翎", gender: "女", age: 26, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longjunfengqing", nameZh: "龙珺峰晴", gender: "女", age: 24, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyijinquan", nameZh: "龙翼瑾泉", gender: "女", age: 28, traitZh: "温婉成熟音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyanhuixiao", nameZh: "龙焱辉潇", gender: "女", age: 21, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longmulinghong", nameZh: "龙暮凌虹", gender: "女", age: 25, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longchengxutao", nameZh: "龙澄旭桃", gender: "女", age: 24, traitZh: "活泼灵动音", sceneZh: "社交互动", lang: "中文" },
  { suffix: "longxiaosongyu", nameZh: "龙潇松雨", gender: "女", age: 24, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyantongxi", nameZh: "龙妍彤溪", gender: "女", age: 28, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxueronghui", nameZh: "龙雪蓉晦", gender: "女", age: 26, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyitingyan", nameZh: "龙漪汀焱", gender: "女", age: 25, traitZh: "爽朗利落音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyijinhong", nameZh: "龙翼瑾鸿", gender: "女", age: 24, traitZh: "爽朗利落音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlanghuishuang", nameZh: "龙朗辉霜", gender: "女", age: 25, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longluyueqin", nameZh: "龙露玥琴", gender: "女", age: 24, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longjinlianji", nameZh: "龙瑾莲霁", gender: "女", age: 25, traitZh: "低沉压抑音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyueximu", nameZh: "龙玥溪暮", gender: "女", age: 25, traitZh: "欢快明朗音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlanjunxu", nameZh: "龙岚珺旭", gender: "女", age: 25, traitZh: "温柔青春音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longlanhuihui", nameZh: "龙兰辉晦", gender: "女", age: 27, traitZh: "搞怪逗趣音", sceneZh: "娱乐搞笑", lang: "中文" },
  { suffix: "longxiaohehui", nameZh: "龙霄鹤晖", gender: "男", age: 24, traitZh: "低沉压抑音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlanxuanxian", nameZh: "龙兰暄弦", gender: "女", age: 26, traitZh: "爽朗利落音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longhuixuanyan", nameZh: "龙晖暄燕", gender: "女", age: 24, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxingyujun", nameZh: "龙星羽珺", gender: "女", age: 25, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyanyuantao", nameZh: "龙妍渊桃", gender: "男", age: 37, traitZh: "爽朗利落音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longsongquanxuan", nameZh: "龙松泉璇", gender: "女", age: 26, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxiaomohong", nameZh: "龙潇沫虹", gender: "女", age: 22, traitZh: "活泼灵动音", sceneZh: "社交互动", lang: "中文" },
  { suffix: "longxinyanshuo", nameZh: "龙昕妍烁", gender: "女", age: 24, traitZh: "活泼灵动音", sceneZh: "社交互动", lang: "中文" },
  { suffix: "longsongbaifeng", nameZh: "龙松柏枫", gender: "男", age: 22, traitZh: "叙事沉浸音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longjiquexue", nameZh: "龙霁鹊雪", gender: "男", age: 24, traitZh: "侠骨柔情音", sceneZh: "古风有声书", lang: "中文" },
  { suffix: "longlangjixuan", nameZh: "龙朗霁萱", gender: "男", age: 24, traitZh: "电台质感音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlanxiaqing", nameZh: "龙岚霞晴", gender: "男", age: 22, traitZh: "温润暖男音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longjunlingtao", nameZh: "龙珺岭桃", gender: "男", age: 24, traitZh: "侠骨柔情音", sceneZh: "古风有声书", lang: "中文" },
  { suffix: "longfengjinhe", nameZh: "龙峰瑾鹤", gender: "男", age: 28, traitZh: "沉稳大气音", sceneZh: "有声阅读", lang: "中文" },
  { suffix: "longbaixingyu", nameZh: "龙柏杏煜", gender: "男", age: 26, traitZh: "侠骨柔情音", sceneZh: "古风有声书", lang: "中文" },
  { suffix: "longshuanghuichuan", nameZh: "龙霜晖川", gender: "女", age: 28, traitZh: "叙事沉浸音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlingzhengtong", nameZh: "龙凌筝彤", gender: "女", age: 29, traitZh: "叙事沉浸音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longjinxilan", nameZh: "龙瑾溪嵐", gender: "女", age: 25, traitZh: "电台质感音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longqingxiangju", nameZh: "龙晴湘菊", gender: "女", age: 25, traitZh: "电台质感音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyaozhiqing", nameZh: "龙瑶芷晴", gender: "女", age: 26, traitZh: "电台质感音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longdieshuangluan", nameZh: "龙蝶霜鸾", gender: "女", age: 40, traitZh: "电台质感音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxuanhongxi", nameZh: "龙萱鸿溪", gender: "男", age: 24, traitZh: "活泼灵动音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyueyuqin", nameZh: "龙月瑜琴", gender: "男", age: 26, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longjuhefeng", nameZh: "龙菊荷风", gender: "男", age: 23, traitZh: "中气充沛音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxianhelan", nameZh: "龙弦荷嵐", gender: "男", age: 28, traitZh: "叙事沉浸音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longqingyanyun", nameZh: "龙晴焱云", gender: "男", age: 42, traitZh: "侠气武侠音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlianliusong", nameZh: "龙莲柳松", gender: "男", age: 28, traitZh: "侠气武侠音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longzhujinxuan", nameZh: "龙竹瑾萱", gender: "男", age: 26, traitZh: "威严领导音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longshuangxuandie", nameZh: "龙霜萱蝶", gender: "女", age: 22, traitZh: "爽朗利落音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longluzhulan", nameZh: "龙露竹澜", gender: "女", age: 22, traitZh: "爽朗利落音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyixiangcheng", nameZh: "龙熠湘澄", gender: "女", age: 19, traitZh: "活泼灵动音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxuanyanyun", nameZh: "龙璇燕云", gender: "女", age: 23, traitZh: "阴郁深沉音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxuanchengdie", nameZh: "龙萱澄蝶", gender: "女", age: 23, traitZh: "强势霸气音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyiyulu", nameZh: "龙漪羽露", gender: "女", age: 25, traitZh: "阴狠毒辣音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longhonglingxue", nameZh: "龙鸿岭雪", gender: "女", age: 25, traitZh: "阴狠毒辣音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyilianxia", nameZh: "龙翼莲霞", gender: "女", age: 28, traitZh: "雍容宫廷音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlulanxuan", nameZh: "龙露岚萱", gender: "女", age: 27, traitZh: "阴狠毒辣音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyizhengmu", nameZh: "龙熠筝暮", gender: "女", age: 24, traitZh: "怯弱自卑音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longhexueling", nameZh: "龙荷雪翎", gender: "女", age: 22, traitZh: "呆萌软糯音", sceneZh: "动漫配音", lang: "中文" },
  { suffix: "longhuishanshuo", nameZh: "龙晖杉朔", gender: "女", age: 16, traitZh: "呆萌软糯音", sceneZh: "动漫配音", lang: "中文" },
  { suffix: "longyifenghe", nameZh: "龙熠枫荷", gender: "女", age: 22, traitZh: "内敛含蓄音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longfengxuanxing", nameZh: "龙风璇杏", gender: "女", age: 22, traitZh: "沉郁心事音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxueyujun", nameZh: "龙雪瑜珺", gender: "女", age: 21, traitZh: "怯弱自卑音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longmolinglian", nameZh: "龙沫岭莲", gender: "女", age: 23, traitZh: "平稳陈述音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longjinlingshuang", nameZh: "龙瑾翎霜", gender: "女", age: 22, traitZh: "呆萌软糯音", sceneZh: "动漫配音", lang: "中文" },
  { suffix: "longweimeiyi", nameZh: "龙薇梅翼", gender: "女", age: 9, traitZh: "呆萌软糯音", sceneZh: "动漫配音", lang: "中文" },
  { suffix: "longxiaquehong", nameZh: "龙霞鹊鸿", gender: "女", age: 22, traitZh: "娇嗲甜腻音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlanwangyi", nameZh: "龙澜望翼", gender: "女", age: 21, traitZh: "细腻深沉音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longxiniyan", nameZh: "龙溪霓燕", gender: "女", age: 24, traitZh: "善解人意音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyufengmo", nameZh: "龙煜枫沫", gender: "女", age: 22, traitZh: "温柔坚韧音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longzhengxike", nameZh: "龙筝溪珂", gender: "女", age: 25, traitZh: "温柔青春音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longjunqingyu", nameZh: "龙珺晴煜", gender: "女", age: 24, traitZh: "大方温和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longtongwangque", nameZh: "龙桐望鹊", gender: "女", age: 24, traitZh: "忧郁深沉音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxueniling", nameZh: "龙雪霓翎", gender: "女", age: 24, traitZh: "电台质感音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyuxiangxia", nameZh: "龙羽湘霞", gender: "女", age: 25, traitZh: "成熟知心音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longfenglanlu", nameZh: "龙风兰露", gender: "男", age: 25, traitZh: "清朗少年音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyuhongche", nameZh: "龙羽鸿澈", gender: "女", age: 72, traitZh: "神秘术士音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlangqingyi", nameZh: "龙朗晴翼", gender: "女", age: 25, traitZh: "呆萌憨直音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlanquancheng", nameZh: "龙嵐泉澄", gender: "女", age: 25, traitZh: "温柔贴心音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longluanyuxu", nameZh: "龙鸾瑜旭", gender: "男", age: 25, traitZh: "正气凛然音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longtinghongxiao", nameZh: "龙汀鸿霄", gender: "女", age: 26, traitZh: "活力童趣音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longfuhuiqing", nameZh: "龙芙晦晴", gender: "女", age: 38, traitZh: "温柔贴心音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longwangyuanxing", nameZh: "龙望渊杏", gender: "女", age: 43, traitZh: "憨厚诙谐音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longquanqingshan", nameZh: "龙泉晴杉", gender: "女", age: 8, traitZh: "温柔贴心音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyaoshuoyu", nameZh: "龙瑶朔瑜", gender: "女", age: 26, traitZh: "温柔贴心音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longhuiluling", nameZh: "龙晦露凌", gender: "女", age: 25, traitZh: "温柔贴心音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longlinbaitong", nameZh: "龙琳柏彤", gender: "女", age: 8, traitZh: "欢乐卡通音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyuxiangzhi", nameZh: "龙羽湘芷", gender: "女", age: 22, traitZh: "柔弱楚楚音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longhexuanlan", nameZh: "龙荷萱澜", gender: "男", age: 24, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longlingchengyi", nameZh: "龙凌澄翼", gender: "男", age: 42, traitZh: "清朗少年音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyanyaolu", nameZh: "龙焱瑶露", gender: "男", age: 42, traitZh: "清俊少年音", sceneZh: "古风有声书", lang: "中文" },
  { suffix: "longtongjichuan", nameZh: "龙彤霁川", gender: "女", age: 25, traitZh: "成熟知心音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlinchengquan", nameZh: "龙麟澄泉", gender: "女", age: 25, traitZh: "柔怯温婉音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longhuiquanqing", nameZh: "龙晖泉晴", gender: "女", age: 7, traitZh: "娇嗲甜腻音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlanlingcan", nameZh: "龙兰凌璨", gender: "女", age: 7, traitZh: "纯真稚嫩音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlanquexiao", nameZh: "龙兰雀潇", gender: "男", age: 25, traitZh: "温润暖男音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longmeitingsong", nameZh: "龙梅汀松", gender: "男", age: 29, traitZh: "温婉成熟音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longbaikehui", nameZh: "龙柏珂晦", gender: "男", age: 26, traitZh: "成熟知心音", sceneZh: "深夜电台", lang: "中文" },
  { suffix: "longtingjinxi", nameZh: "龙汀瑾溪", gender: "男", age: 25, traitZh: "憨厚诙谐音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longcanlingying", nameZh: "龙璨凌莹", gender: "女", age: 25, traitZh: "温柔贴心音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyanlianyao", nameZh: "龙焱涟瑶", gender: "女", age: 16, traitZh: "灵动戏腔音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longximusong", nameZh: "龙曦暮松", gender: "女", age: 28, traitZh: "鬼马调皮音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longchexueyue", nameZh: "龙澈雪月", gender: "女", age: 7, traitZh: "憨厚诙谐音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longhuichengfu", nameZh: "龙晖澄芙", gender: "男", age: 8, traitZh: "慵懒童趣音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longchengdieshuo", nameZh: "龙澄蝶烁", gender: "男", age: 24, traitZh: "少年指挥音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlanyimo", nameZh: "龙澜熠沫", gender: "女", age: 25, traitZh: "温柔贴心音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longchuanrongshuo", nameZh: "龙川蓉朔", gender: "中性", age: 25, traitZh: "沉稳大气音", sceneZh: "古风有声书", lang: "中文" },
  { suffix: "longxiuquanwang", nameZh: "龙岫泉望", gender: "女", age: 25, traitZh: "温甜柔美音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longquediechuan", nameZh: "龙鹊蝶川", gender: "女", age: 27, traitZh: "温柔贴心音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyanyuju", nameZh: "龙妍煜菊", gender: "女", age: 25, traitZh: "憨萌逗趣音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longnilanfeng", nameZh: "龙霓岚凤", gender: "女", age: 26, traitZh: "成熟知心音", sceneZh: "有声阅读", lang: "中文" },
  { suffix: "longxiangxiaozheng", nameZh: "龙湘霄筝", gender: "女", age: 7, traitZh: "活泼灵动音", sceneZh: "社交互动", lang: "中文" },
  { suffix: "longfengmeiwei", nameZh: "龙峰梅薇", gender: "女", age: 24, traitZh: "温柔贴心音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longjuqinshuang", nameZh: "龙菊琴霜", gender: "男", age: 42, traitZh: "温润暖男音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyandierong", nameZh: "龙焱蝶蓉", gender: "男", age: 24, traitZh: "惊恐不安音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longkechengji", nameZh: "龙珂澄霁", gender: "男", age: 24, traitZh: "清朗少年音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlanbailan", nameZh: "龙嵐柏澜", gender: "女", age: 25, traitZh: "温柔贴心音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longlanjunxing", nameZh: "龙澜珺星", gender: "女", age: 25, traitZh: "温婉成熟音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longshuangjinlan", nameZh: "龙霜瑾澜", gender: "女", age: 25, traitZh: "御姐成熟音", sceneZh: "有声书配音", lang: "中文" },
  { suffix: "longjinlianxiao", nameZh: "龙瑾涟晓", gender: "女", age: 26, traitZh: "沉稳有力音", sceneZh: "有声阅读", lang: "中文" },
  { suffix: "longlanfengyu", nameZh: "龙嵐凤羽", gender: "女", age: 24, traitZh: "成熟沉稳音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longshuangchexiao", nameZh: "龙霜澈霄", gender: "女", age: 23, traitZh: "傲娇闺秀音", sceneZh: "古风有声书", lang: "中文" },
  { suffix: "longlingjinquan", nameZh: "龙凌瑾泉", gender: "女", age: 24, traitZh: "元气少女音", sceneZh: "社交互动", lang: "中文" },
  { suffix: "longlanlingying", nameZh: "龙嵐凌莹", gender: "女", age: 24, traitZh: "灵动少女音", sceneZh: "社交互动", lang: "中文" },
  { suffix: "longlanqinluan", nameZh: "龙兰琴鸾", gender: "女", age: 25, traitZh: "沉稳知性音", sceneZh: "知识分享", lang: "中文" },
  { suffix: "longxiaoyulan", nameZh: "龙霄羽岚", gender: "女", age: 20, traitZh: "成熟御姐音", sceneZh: "有声书配音", lang: "中文" },
  { suffix: "longyuxiangfeng", nameZh: "龙煜湘凤", gender: "女", age: 26, traitZh: "温柔知性音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longxuefenghe", nameZh: "龙雪风荷", gender: "女", age: 22, traitZh: "甜萌可爱音", sceneZh: "社交互动", lang: "中文" },
  { suffix: "longlingtingxiu", nameZh: "龙岭汀岫", gender: "女", age: 29, traitZh: "温柔邻家音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longkeyanyu", nameZh: "龙珂焱瑜", gender: "女", age: 26, traitZh: "稳重沉着音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyanhonglin", nameZh: "龙焱虹琳", gender: "女", age: 27, traitZh: "温柔俏皮音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longxiaoxianglian", nameZh: "龙潇湘涟", gender: "女", age: 24, traitZh: "御姐成熟音", sceneZh: "有声书配音", lang: "中文" },
  { suffix: "longlingxingyi", nameZh: "龙岭星翼", gender: "女", age: 27, traitZh: "成熟御姐音", sceneZh: "有声书配音", lang: "中文" },
  { suffix: "longdiemujun", nameZh: "龙蝶暮珺", gender: "女", age: 9, traitZh: "柔弱楚楚音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longhuilingfu", nameZh: "龙辉岭芙", gender: "女", age: 25, traitZh: "温柔俏皮音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longjishuangmu", nameZh: "龙霁霜暮", gender: "女", age: 25, traitZh: "善解人意音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longjushuorong", nameZh: "龙菊朔蓉", gender: "女", age: 25, traitZh: "温柔知性音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longtaoxingque", nameZh: "龙桃星鹊", gender: "男", age: 25, traitZh: "清朗少年音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longsonglinwang", nameZh: "龙松麟望", gender: "男", age: 36, traitZh: "温润磁性音", sceneZh: "深夜电台", lang: "中文" },
  { suffix: "longxiaoyanling", nameZh: "龙潇焱岭", gender: "男", age: 28, traitZh: "温润磁性音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longhuiheting", nameZh: "龙晦荷汀", gender: "男", age: 25, traitZh: "清朗少年音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxinchuanyi", nameZh: "龙昕川漪", gender: "男", age: 24, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longshanxiulian", nameZh: "龙杉岫涟", gender: "男", age: 26, traitZh: "善解人意音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longlangjishuo", nameZh: "龙朗霁朔", gender: "女", age: 25, traitZh: "温柔亲和音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyanchuantao", nameZh: "龙焱川桃", gender: "女", age: 25, traitZh: "柔怯温婉音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longxiaolinzhi", nameZh: "龙霄琳芷", gender: "女", age: 26, traitZh: "温婉成熟音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longhuiyingwang", nameZh: "龙晦樱望", gender: "女", age: 24, traitZh: "温柔知性音", sceneZh: "知识分享", lang: "中文" },
  { suffix: "longyuchuanlan", nameZh: "龙瑜川岚", gender: "男", age: 29, traitZh: "温婉成熟音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longjinmeicheng", nameZh: "龙瑾梅澄", gender: "男", age: 27, traitZh: "成熟沉稳音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longluanlanju", nameZh: "龙鸾岚菊", gender: "女", age: 25, traitZh: "元气少女音", sceneZh: "社交互动", lang: "中文" },
  { suffix: "longjintongxi", nameZh: "龙瑾彤溪", gender: "女", age: 25, traitZh: "雍容宫廷音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxulianxia", nameZh: "龙旭莲霞", gender: "女", age: 24, traitZh: "温甜柔美音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longxinglianwei", nameZh: "龙杏涟薇", gender: "女", age: 25, traitZh: "雍容宫廷音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longweihezheng", nameZh: "龙薇荷筝", gender: "女", age: 21, traitZh: "甜萌可爱音", sceneZh: "社交互动", lang: "中文" },
  { suffix: "longrongshuangxuan", nameZh: "龙蓉霜暄", gender: "女", age: 25, traitZh: "温柔知性音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longcanruishuang", nameZh: "龙璨蕊霜", gender: "女", age: 8, traitZh: "甜萌可爱音", sceneZh: "社交互动", lang: "中文" },
  { suffix: "longyuetongling", nameZh: "龙玥彤岭", gender: "女", age: 24, traitZh: "温柔贴心音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyunlingbai", nameZh: "龙云凌柏", gender: "女", age: 8, traitZh: "甜萌可爱音", sceneZh: "动漫配音", lang: "中文" },
  { suffix: "longchuanxuxing", nameZh: "龙川旭杏", gender: "女", age: 24, traitZh: "温润磁性音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longkejinhui", nameZh: "龙珂瑾晖", gender: "女", age: 24, traitZh: "温甜柔美音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longxuchengrui", nameZh: "龙旭澄蕊", gender: "女", age: 24, traitZh: "温柔贴心音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longshandiefeng", nameZh: "龙杉蝶风", gender: "女", age: 20, traitZh: "温甜柔美音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longlanfengxia", nameZh: "龙澜枫霞", gender: "女", age: 24, traitZh: "温柔贴心音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longfengxiaolin", nameZh: "龙风晓琳", gender: "男", age: 25, traitZh: "温润暖男音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyuejinxiu", nameZh: "龙玥瑾岫", gender: "男", age: 24, traitZh: "成熟稳重音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longhexiaofeng", nameZh: "龙荷潇峰", gender: "男", age: 37, traitZh: "硬朗阳刚音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longzhuyuebai", nameZh: "龙竹玥柏", gender: "女", age: 25, traitZh: "阳光开朗音", sceneZh: "知识分享", lang: "中文" },
  { suffix: "longhuiliantong", nameZh: "龙晖莲彤", gender: "女", age: 25, traitZh: "温柔贴心音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longhongyanxuan", nameZh: "龙虹妍璇", gender: "女", age: 25, traitZh: "威严将领音", sceneZh: "体育解说", lang: "中文" },
  { suffix: "longshanyancan", nameZh: "龙杉焱璨", gender: "女", age: 25, traitZh: "热忱推荐音", sceneZh: "商务汇报", lang: "中文" },
  { suffix: "longxiangkeyao", nameZh: "龙湘珂瑶", gender: "女", age: 24, traitZh: "活泼开朗音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longfenghechuan", nameZh: "龙枫荷川", gender: "女", age: 25, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyunfuhong", nameZh: "龙云芙鸿", gender: "女", age: 25, traitZh: "标准播音音", sceneZh: "新闻播报", lang: "中文" },
  { suffix: "longlanweiyue", nameZh: "龙岚薇玥", gender: "女", age: 25, traitZh: "温柔知心音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longfuxuyu", nameZh: "龙芙旭羽", gender: "女", age: 24, traitZh: "专业解说音", sceneZh: "体育解说", lang: "中文" },
  { suffix: "longyuxuanmei", nameZh: "龙雨暄梅", gender: "女", age: 24, traitZh: "温柔哀婉音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longbaifengshuo", nameZh: "龙柏凤朔", gender: "女", age: 24, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longwangmeican", nameZh: "龙望梅璨", gender: "女", age: 23, traitZh: "爽朗大笑音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyanzhihe", nameZh: "龙焱芷荷", gender: "女", age: 8, traitZh: "温甜柔美音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longxiuxiayu", nameZh: "龙岫霞煜", gender: "女", age: 24, traitZh: "温甜柔美音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longxianlingling", nameZh: "龙弦凌岭", gender: "女", age: 25, traitZh: "磁性质感音", sceneZh: "深夜电台", lang: "中文" },
  { suffix: "longlanrongshuo", nameZh: "龙嵐蓉朔", gender: "女", age: 26, traitZh: "搞怪卡通音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyiqinghui", nameZh: "龙漪晴晦", gender: "女", age: 60, traitZh: "慈祥祖母音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longchezhuyu", nameZh: "龙澈竹雨", gender: "女", age: 25, traitZh: "自然亲和音", sceneZh: "智能助手", lang: "中文" },
  { suffix: "longchengliansong", nameZh: "龙澄涟松", gender: "女", age: 23, traitZh: "游戏解说音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longtingquezhu", nameZh: "龙汀鹊竹", gender: "女", age: 23, traitZh: "运动喘息音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longtongmuyuan", nameZh: "龙彤暮渊", gender: "男", age: 38, traitZh: "焦躁烦闷音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyuxiulan", nameZh: "龙雨岫兰", gender: "男", age: 19, traitZh: "撒娇甜蜜音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxiucheyu", nameZh: "龙岫澈雨", gender: "男", age: 26, traitZh: "温润磁性音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longlangjunji", nameZh: "龙朗珺霁", gender: "女", age: 24, traitZh: "温柔知性音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longlianyunxia", nameZh: "龙莲云霞", gender: "女", age: 26, traitZh: "凌厉剑气音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longmoyulu", nameZh: "龙沫雨露", gender: "女", age: 19, traitZh: "热血激昂音", sceneZh: "体育解说", lang: "中文" },
  { suffix: "longjinlinfeng", nameZh: "龙瑾麟枫", gender: "女", age: 25, traitZh: "大方温和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longqinghexi", nameZh: "龙晴鹤溪", gender: "女", age: 24, traitZh: "温柔知心音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyilanni", nameZh: "龙漪兰霓", gender: "女", age: 21, traitZh: "热血激昂音", sceneZh: "体育解说", lang: "中文" },
  { suffix: "longlanxinglin", nameZh: "龙岚星琳", gender: "女", age: 42, traitZh: "智慧祖母音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longjimoyan", nameZh: "龙霁沫燕", gender: "女", age: 24, traitZh: "温柔贴心音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longruirongxiu", nameZh: "龙蕊蓉岫", gender: "男", age: 26, traitZh: "随性自在音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyingtaoji", nameZh: "龙莹桃霁", gender: "男", age: 25, traitZh: "成熟稳重音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longfengxindie", nameZh: "龙风昕蝶", gender: "女", age: 26, traitZh: "亲和自然音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxuanyinglu", nameZh: "龙萱樱露", gender: "女", age: 25, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longqinghuilang", nameZh: "龙晴辉朗", gender: "女", age: 24, traitZh: "知性姐姐音", sceneZh: "知识分享", lang: "中文" },
  { suffix: "longronghongxue", nameZh: "龙蓉虹雪", gender: "女", age: 24, traitZh: "专业解说音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longruimoliu", nameZh: "龙蕊沫柳", gender: "女", age: 28, traitZh: "自然亲和音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longhexiaoxuan", nameZh: "龙荷潇璇", gender: "男", age: 38, traitZh: "文雅书卷音", sceneZh: "古风有声书", lang: "中文" },
  { suffix: "longchengyuhui", nameZh: "龙澄瑜辉", gender: "女", age: 8, traitZh: "调皮少年音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxuanlinju", nameZh: "龙萱琳菊", gender: "女", age: 22, traitZh: "大方温和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longlinlinying", nameZh: "龙麟琳莹", gender: "女", age: 22, traitZh: "伤感低回音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyilangyan", nameZh: "龙熠朗燕", gender: "女", age: 24, traitZh: "温柔知性音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longshuanglanhui", nameZh: "龙霜岚晖", gender: "女", age: 25, traitZh: "大方温和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyiyuxian", nameZh: "龙漪瑜弦", gender: "女", age: 8, traitZh: "温柔知性音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longsonglinhe", nameZh: "龙松琳鹤", gender: "女", age: 25, traitZh: "温柔知性音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longxuanzhilin", nameZh: "龙萱芷琳", gender: "女", age: 25, traitZh: "耐心教导音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longfengyuxiao", nameZh: "龙峰雨霄", gender: "男", age: 29, traitZh: "温润磁性音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longxiaoyihe", nameZh: "龙霄漪荷", gender: "男", age: 42, traitZh: "温润暖男音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlianyingyue", nameZh: "龙莲樱玥", gender: "女", age: 28, traitZh: "成熟知心音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longqingyiyao", nameZh: "龙晴翼瑶", gender: "女", age: 25, traitZh: "大方温和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longshuangweihe", nameZh: "龙霜薇鹤", gender: "女", age: 24, traitZh: "惊奇讶异音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longquantaolan", nameZh: "龙泉桃嵐", gender: "女", age: 27, traitZh: "成熟沉稳音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longchuanyingyue", nameZh: "龙川樱玥", gender: "男", age: 38, traitZh: "腹黑深沉音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longliutaohong", nameZh: "龙柳桃虹", gender: "女", age: 22, traitZh: "傲娇俏皮音", sceneZh: "社交互动", lang: "中文" },
  { suffix: "longrongxianyu", nameZh: "龙蓉弦煜", gender: "女", age: 26, traitZh: "雍容宫廷音", sceneZh: "古风有声书", lang: "中文" },
  { suffix: "longluanxuanling", nameZh: "龙鸾萱凌", gender: "女", age: 25, traitZh: "温柔姐姐音", sceneZh: "知识分享", lang: "中文" },
  { suffix: "longhefenglian", nameZh: "龙鹤峰涟", gender: "女", age: 24, traitZh: "清亮明朗音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longjunfuyu", nameZh: "龙珺芙羽", gender: "女", age: 23, traitZh: "慵懒童趣音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longfengqinji", nameZh: "龙峰琴霁", gender: "女", age: 26, traitZh: "温润磁性音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyingyiyu", nameZh: "龙樱翼瑜", gender: "女", age: 23, traitZh: "萌宠拟声音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longchezhihong", nameZh: "龙澈芷虹", gender: "女", age: 26, traitZh: "耐心教导音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longfulingmu", nameZh: "龙芙凌暮", gender: "女", age: 24, traitZh: "正太变声音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxuansongxing", nameZh: "龙璇松杏", gender: "女", age: 24, traitZh: "柔弱楚楚音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longhecherong", nameZh: "龙鹤澈蓉", gender: "女", age: 16, traitZh: "清亮明朗音", sceneZh: "动漫配音", lang: "中文" },
  { suffix: "longlianlanyuan", nameZh: "龙莲嵐渊", gender: "女", age: 25, traitZh: "温柔贴心音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longxiutongni", nameZh: "龙岫桐霓", gender: "女", age: 24, traitZh: "清亮明朗音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longtongheji", nameZh: "龙桐荷霁", gender: "女", age: 25, traitZh: "温润磁性音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longfengmohui", nameZh: "龙枫沫晖", gender: "女", age: 26, traitZh: "温柔贴心音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longquanxuanshuang", nameZh: "龙泉暄霜", gender: "女", age: 23, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longlinheyi", nameZh: "龙麟荷熠", gender: "女", age: 22, traitZh: "温柔贴心音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longhuisongxiao", nameZh: "龙晦松晓", gender: "女", age: 27, traitZh: "御姐成熟音", sceneZh: "有声书配音", lang: "中文" },
  { suffix: "longyiyushuo", nameZh: "龙翼雨烁", gender: "女", age: 14, traitZh: "威严将领音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxinyuanxing", nameZh: "龙昕渊星", gender: "女", age: 7, traitZh: "慵懒童趣音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longxiaoxingyi", nameZh: "龙晓星漪", gender: "女", age: 23, traitZh: "灵动少女音", sceneZh: "社交互动", lang: "中文" },
  { suffix: "longlianjinxing", nameZh: "龙涟瑾星", gender: "女", age: 26, traitZh: "温柔知性音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longshanzhengqin", nameZh: "龙杉筝琴", gender: "女", age: 24, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longxuantaoshuo", nameZh: "龙萱桃烁", gender: "女", age: 9, traitZh: "元气活力音", sceneZh: "动漫配音", lang: "中文" },
  { suffix: "longlingweiluan", nameZh: "龙翎薇鸾", gender: "女", age: 24, traitZh: "雍容宫廷音", sceneZh: "古风有声书", lang: "中文" },
  { suffix: "longfengxiuche", nameZh: "龙凤岫澈", gender: "女", age: 24, traitZh: "温柔邻家音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longlinshuoxi", nameZh: "龙琳朔溪", gender: "女", age: 23, traitZh: "温柔知性音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longyaofenghe", nameZh: "龙瑶凤鹤", gender: "女", age: 23, traitZh: "磁性质感音", sceneZh: "深夜电台", lang: "中文" },
  { suffix: "longyucanxiao", nameZh: "龙雨璨晓", gender: "女", age: 22, traitZh: "清亮明朗音", sceneZh: "社交互动", lang: "中文" },
  { suffix: "longxilanque", nameZh: "龙溪澜雀", gender: "女", age: 24, traitZh: "柔怯温婉音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longcheqinyi", nameZh: "龙澈琴漪", gender: "女", age: 25, traitZh: "清亮明朗音", sceneZh: "社交互动", lang: "中文" },
  { suffix: "longxuequanshuo", nameZh: "龙雪泉朔", gender: "女", age: 24, traitZh: "磁性质感音", sceneZh: "深夜电台", lang: "中文" },
  { suffix: "longshanyuxing", nameZh: "龙杉瑜星", gender: "女", age: 25, traitZh: "灵动少女音", sceneZh: "社交互动", lang: "中文" },
  { suffix: "longlantongluan", nameZh: "龙岚彤鸾", gender: "女", age: 24, traitZh: "大气司仪音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longbaichexuan", nameZh: "龙柏澈萱", gender: "男", age: 28, traitZh: "磁性质感音", sceneZh: "深夜电台", lang: "中文" },
  { suffix: "longlangmoyue", nameZh: "龙朗沫玥", gender: "男", age: 42, traitZh: "沉稳内敛音", sceneZh: "有声阅读", lang: "中文" },
  { suffix: "longwangjixi", nameZh: "龙望霁溪", gender: "男", age: 25, traitZh: "睿智亲和音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longshuangqinque", nameZh: "龙霜琴雀", gender: "女", age: 25, traitZh: "成熟知心音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longkeyuecan", nameZh: "龙珂月璨", gender: "女", age: 7, traitZh: "搞怪卡通音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyuanruiling", nameZh: "龙渊蕊翎", gender: "女", age: 23, traitZh: "温柔知性音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longquefengshuo", nameZh: "龙雀枫朔", gender: "女", age: 26, traitZh: "温柔姐姐音", sceneZh: "知识分享", lang: "中文" },
  { suffix: "longxishuoxuan", nameZh: "龙溪烁璇", gender: "女", age: 26, traitZh: "清亮明朗音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longtongquanxi", nameZh: "龙彤泉溪", gender: "女", age: 24, traitZh: "温柔姐姐音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longhetongcan", nameZh: "龙鹤彤璨", gender: "女", age: 25, traitZh: "磁性质感音", sceneZh: "古风有声书", lang: "中文" },
  { suffix: "longyuyuzheng", nameZh: "龙瑜羽筝", gender: "女", age: 24, traitZh: "温柔亲和音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longjunqueyu", nameZh: "龙珺鹊羽", gender: "女", age: 25, traitZh: "自然亲和音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longzhenglanyao", nameZh: "龙筝兰瑶", gender: "女", age: 8, traitZh: "清亮明朗音", sceneZh: "社交互动", lang: "中文" },
  { suffix: "longqingxiaoxiang", nameZh: "龙晴霄湘", gender: "女", age: 27, traitZh: "自信从容音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longyueyaoling", nameZh: "龙月瑶翎", gender: "男", age: 25, traitZh: "成熟沉稳音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longlinhongxi", nameZh: "龙麟鸿溪", gender: "男", age: 22, traitZh: "青年朝气音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longchengtingtong", nameZh: "龙澄汀桐", gender: "女", age: 26, traitZh: "尖亮穿透音", sceneZh: "新闻播报", lang: "中文" },
  { suffix: "longtonghewei", nameZh: "龙桐荷薇", gender: "女", age: 28, traitZh: "低沉深邃音", sceneZh: "有声书配音", lang: "中文" },
  { suffix: "longlanjulu", nameZh: "龙澜菊露", gender: "女", age: 25, traitZh: "磁性质感音", sceneZh: "深夜电台", lang: "中文" },
  { suffix: "longyingdielin", nameZh: "龙莹蝶琳", gender: "男", age: 42, traitZh: "热血激昂音", sceneZh: "体育解说", lang: "中文" },
  { suffix: "longyulianrong", nameZh: "龙羽莲蓉", gender: "男", age: 28, traitZh: "沉稳解说音", sceneZh: "有声阅读", lang: "中文" },
  { suffix: "longhuiyanxing", nameZh: "龙辉焱杏", gender: "男", age: 42, traitZh: "沉稳解说音", sceneZh: "有声阅读", lang: "中文" },
  { suffix: "longquexuhui", nameZh: "龙雀旭辉", gender: "女", age: 35, traitZh: "自然亲和音", sceneZh: "日常对话", lang: "中文" },
  { suffix: "longkeyuwang", nameZh: "龙珂煜望", gender: "女", age: 27, traitZh: "专业解说音", sceneZh: "体育解说", lang: "中文" },
  { suffix: "longyushanluan", nameZh: "龙瑜杉鸾", gender: "女", age: 25, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "longweiquancheng", nameZh: "龙薇泉澄", gender: "女", age: 26, traitZh: "温柔亲和音", sceneZh: "情感陪伴", lang: "中文" },
  { suffix: "loongolivialin", nameZh: "Olivia Lin", gender: "女", age: 28, traitZh: "温柔知性音", sceneZh: "情感陪伴", lang: "英文" },
  { suffix: "loonglunawang", nameZh: "Luna Wang", gender: "女", age: 21, traitZh: "智能助手音", sceneZh: "日常对话", lang: "英文" },
  { suffix: "loongalexanderhu", nameZh: "Alexander Hu", gender: "男", age: 27, traitZh: "复古磁带音", sceneZh: "日常对话", lang: "英文" },
  { suffix: "loongnorahu", nameZh: "Nora Hu", gender: "女", age: 25, traitZh: "活泼灵动音", sceneZh: "日常对话", lang: "英文" },
  { suffix: "loongadriangao", nameZh: "Adrian Gao", gender: "男", age: 22, traitZh: "沉稳大气音", sceneZh: "有声阅读", lang: "英文" },
  { suffix: "loongjameszhao", nameZh: "James Zhao", gender: "男", age: 28, traitZh: "新闻播报音", sceneZh: "日常对话", lang: "英文" },
  { suffix: "loongryanma", nameZh: "Ryan Ma", gender: "男", age: 38, traitZh: "电子潮流音", sceneZh: "日常对话", lang: "英文" },
  { suffix: "loongivyhu", nameZh: "Ivy Hu", gender: "女", age: 54, traitZh: "自信从容音", sceneZh: "演讲朗诵", lang: "英文" },
  { suffix: "longyingbaozi", nameZh: "龙应宝子", gender: "女", age: 25, traitZh: "邻家亲切音", sceneZh: "标准通用型客服", lang: "中文" },
  { suffix: "longyingyali", nameZh: "龙应压力", gender: "男", age: 27, traitZh: "理性告知音", sceneZh: "初期催收提醒客服", lang: "中文" },
  { suffix: "longyingyueyue", nameZh: "龙应越越", gender: "女", age: 22, traitZh: "耐心专业音", sceneZh: "讲解引导型客服", lang: "中文" },
  { suffix: "longyingxiaola", nameZh: "龙应小辣", gender: "女", age: 25, traitZh: "稳健顾问音", sceneZh: "理财咨询型客服", lang: "中文" },
  { suffix: "longyingyifan", nameZh: "龙应一帆", gender: "男", age: 30, traitZh: "启蒙导师音", sceneZh: "引导新手型客服", lang: "中文" },
  { suffix: "longyinglanxin", nameZh: "龙应岚心", gender: "女", age: 23, traitZh: "理性告知音", sceneZh: "账单提醒型客服", lang: "中文" },
  { suffix: "longyingmuyu", nameZh: "龙应沐语", gender: "女", age: 25, traitZh: "温柔亲和音", sceneZh: "标准通用型客服", lang: "中文" },
  { suffix: "longyingyulu", nameZh: "龙应玉路", gender: "女", age: 22, traitZh: "真诚邀请音", sceneZh: "新品推荐型客服", lang: "中文" },
  { suffix: "longyingmomo", nameZh: "龙应末末", gender: "男", age: 30, traitZh: "诚恳稳重音", sceneZh: "理财顾问型客服", lang: "中文" },
  { suffix: "longyingshiyu", nameZh: "龙应时渝", gender: "女", age: 30, traitZh: "干练响应音", sceneZh: "标准通用型客服", lang: "中文" },
  { suffix: "longyinghaitai", nameZh: "龙应海台", gender: "女", age: 28, traitZh: "耐心包容音", sceneZh: "医院社区引导型客服", lang: "中文" },
  { suffix: "longyinghaiyuan", nameZh: "龙应海远", gender: "女", age: 35, traitZh: "克制礼貌音", sceneZh: "监察回访型客服", lang: "中文" },
  { suffix: "longyingwumao", nameZh: "龙应吾茂", gender: "男", age: 30, traitZh: "客观冷静音", sceneZh: "核保理赔型客服", lang: "中文" },
];
