import { afterEach, expect, it, vi } from "vitest";
vi.mock("./gcs.js", () => ({ readGcsPrefixRevision: vi.fn() }));
import { createTemplateCatalogEvents } from "./manhuaTemplateCatalogEvents";
afterEach(() => vi.useRealTimers());
it("跨进程新增/更新版本会通知，未改变不重复下载目录，无订阅时停止", async () => {
  vi.useFakeTimers();
  const read = vi.fn().mockResolvedValue("first");
  const bus = createTemplateCatalogEvents(read, 1000);
  const a = vi.fn(), b = vi.fn();
  const stopA = bus.subscribe(a), stopB = bus.subscribe(b);
  await vi.advanceTimersByTimeAsync(0);
  expect(read).toHaveBeenCalledTimes(1);
  expect(a).toHaveBeenCalledTimes(1);
  await vi.advanceTimersByTimeAsync(1000);
  expect(a).toHaveBeenCalledTimes(1);
  read.mockResolvedValue("updated");
  await vi.advanceTimersByTimeAsync(1000);
  expect(a).toHaveBeenCalledTimes(2);
  expect(b).toHaveBeenLastCalledWith(bus.revision());
  stopA(); stopB();
  const calls = read.mock.calls.length;
  await vi.advanceTimersByTimeAsync(5000);
  expect(read).toHaveBeenCalledTimes(calls);
});
it("读取失败保持旧目录并恢复重试；本进程发布立即通知", async () => {
  vi.useFakeTimers();
  const read = vi.fn().mockResolvedValueOnce("a").mockRejectedValueOnce(new Error("storage offline")).mockResolvedValue("b");
  const bus = createTemplateCatalogEvents(read, 1000), listener = vi.fn();
  const stop = bus.subscribe(listener);
  await vi.advanceTimersByTimeAsync(0);
  await vi.advanceTimersByTimeAsync(1000);
  expect(listener).toHaveBeenCalledTimes(1);
  await vi.advanceTimersByTimeAsync(1000);
  expect(listener).toHaveBeenCalledTimes(2);
  bus.publish();
  expect(listener).toHaveBeenCalledTimes(3);
  stop();
});
it("慢读取不重叠，离开页面后不发送迟到通知", async () => {
  vi.useFakeTimers();
  let resolve!: (revision: string) => void;
  const read = vi.fn(() => new Promise<string>(done => { resolve = done; }));
  const bus = createTemplateCatalogEvents(read, 1000), listener = vi.fn();
  const stop = bus.subscribe(listener);
  await vi.advanceTimersByTimeAsync(5000);
  expect(read).toHaveBeenCalledTimes(1);
  stop(); resolve("late");
  await vi.advanceTimersByTimeAsync(0);
  expect(listener).not.toHaveBeenCalled();
});
