CREATE TABLE `video_submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`videoUrl` text NOT NULL,
	`thumbnailUrl` text,
	`duration` int,
	`category` varchar(100),
	`viralScore` int,
	`scoreDetails` json,
	`scoreStatus` enum('pending','scoring','scored','failed') NOT NULL DEFAULT 'pending',
	`licenseAgreed` int NOT NULL DEFAULT 0,
	`licenseVersion` varchar(20) DEFAULT '1.0',
	`licenseAgreedAt` timestamp,
	`creditsRewarded` int NOT NULL DEFAULT 0,
	`rewardedAt` timestamp,
	`showcaseStatus` enum('private','pending_review','showcased','rejected') NOT NULL DEFAULT 'private',
	`adminNotes` text,
	`viewCount` int NOT NULL DEFAULT 0,
	`likeCount` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `video_submissions_id` PRIMARY KEY(`id`)
);
